### ISSUE TITLE
Enable training/inference with half-precision (float16)

### ISSUE THREAD

**Issue by dylanbannon** [vanvalenlab/deepcell-tf#112]
What is it and how does it work?

**Comment by willgraf** [comment]
As discussed in #436, [there are float16 issues with both the ImageDataGenerators and the model zoo](https://github.com/vanvalenlab/deepcell-tf/pull/436#issuecomment-713227234).

**Comment by willgraf** [comment]
It looks like this is supported as [mixed precision](https://www.tensorflow.org/guide/mixed_precision) in TensorFlow 2.

**Comment by willgraf** [comment]
This is indeed supported natively by TensorFlow 2:

```
from tensorflow.keras import mixed_precision

# On TPUs, use 'mixed_bfloat16' instead
mixed_precision.experimental.set_policy('mixed_float16')

# On TensorFlow 2.4.1:
# mixed_precision.set_global_policy('mixed_float16')
```

I tried training the Nuclear Segmentation notebook using the mixed-precision above. However, I found that it caused a significant slowdown during training. (epoch goes from 10 minutes to 60+ minutes). I'm not sure if this is due to our data generators or something about our PanOpticNet model architecture - more debugging is required.

**Comment by willgraf** [comment]
Mixed precision works in TensorFlow 2.4.1!

However, it looks like `std` normalization has an issue with mixed precision: 

```
TypeError: Input 'filter' of 'DepthwiseConv2dNative' Op has type float32 that does not match type float16 of argument 'input'.
```

**Comment by willgraf** [comment]
While #490 does allow mixed-precision training without any warnings or errors, it does not seem to improve training performance. I get roughly the same training time (running the Nuclear Segmentation PanOpticNet notebook) using mixed precision and float32 while testing different settings (Location, normalization method, interpolation upsample_type, etc).

That said, mixed-precision DOES enable much larger batch sizes than with float32 mode, so it is indeed working.
