### ISSUE TITLE
README in directories to describe contents of sub-directories

### ISSUE THREAD

**Issue by msschwartz21** [vanvalenlab/deepcell-tf#138]
Currently, in the scripts directory it's difficult to understand what each of the sub-directories is for and what to expect inside. A README file that describes the contents of each sub-directory could alleviate this problem without needing to abandon the organization of sub-directories.

**Comment by ngreenwald** [comment]
As well as maybe a brief description in the overall README for getting started; for example, a pointer to the scripts/misc folder for example code of how to generate your own notebook so people can dive right in.

**Comment by willgraf** [comment]
Created a PR for README files in `model_zoo`, `notebooks` and `datasets`.  The `model_zoo` README can definitely use a lot more fleshing out, but at least a simple note describing what is in the module is better than nothing.

I think the `layers` are so keras-similar that a README is unnecessary, and that `image_generators` is like-wise pretty self-explanatory.
