### ISSUE TITLE
Generate full path to data when creating training notebook

### ISSUE THREAD

**Issue by ngreenwald** [vanvalenlab/deepcell-tf#146]
Currently when a new training notebook is generated following the template in scripts/misc/miscellaneous for sample-based segmentation, the full path to the data is not provided. Specifically, this line from Interior-Edge%20Segmentation%202D%20Sample%20Based.ipynb
```
# DATA_FILE should be a npz file, preferably from `make_training_data`
DATA_FILE = os.path.join(DATA_DIR, filename)
```

is missing. Instead, DATA_FILE and DATA_DIR are passed separately to train_model_sample. 
However, DATA_FILE has not been modified yet and just represents the name of the directory, not the full path. This results in directory not found error.

**Comment by willgraf** [comment]
Thanks! Nice find. This is due to a refactoring of `deepcell.training` functions that did not manage to get updated in `deepcell.notebooks`.

We will likely be re-configuring `deepcell.notebooks` to use [Papermill](https://github.com/nteract/papermill)
