### ISSUE TITLE
Tracking support for multi-channel X data

### ISSUE THREAD

**Issue by MekWarrior** [vanvalenlab/deepcell-tf#149]
Tracking.py (as well as its associated data generator) currently only support grayscale images. Training and tracking should be robust to images with multiple channels (i.e. RGB).

**Comment by willgraf** [comment]
`tracking.py` has been deprecated for github.com/vanvalenlab/deepcell-tracking.

The image data generator still needs to be modified to enable multi-channel X data, though. There might be a lot of unnecessary functions in the image data generator that could be imported from `deepcell-tracking`.
