### ISSUE TITLE
Image suite for training models for MIBI images

### ISSUE THREAD

**Issue by manugarciaquismondo** [vanvalenlab/deepcell-tf#157]
Greetings,

We managed to run the notebook _Interior-Edge Segmentation 2D Fully Convolutional_ and trained a DeepCell model by using the dataset _https://deepcell-data.s3.amazonaws.com/nuclei/HeLa_S3.npz_.

Our aim is to use DeepCell to train a model with MIBI images. We have found that, in the webpage _http://www.deepcell.org/predict_, a model called **mibi** is available for training. Can you please provide such a model (in the form of a matrix of model weights in _.h5_ format) and the image suite that was used to train this model (in the form of a _.npz_ file)?

Thank you very much,

**Comment by willgraf** [comment]
Hi,

While it is not easy for me to share the .h5 file, I can provide a notebook that walks through how we trained the MIBI model.

In regards to data, we used data that we did not generate, so I will talk with the owners of the data to see if it is OK to share.

**Comment by manugarciaquismondo** [comment]
Greetings,

Thank you for your prompt reply. Since it is not easy to share the .h5 file, can you please provide a notebook that I can use to train our MIBI model?

Thank you,
