### ISSUE TITLE
Train and predicted images of different sizes

### ISSUE THREAD

**Issue by manugarciaquismondo** [vanvalenlab/deepcell-tf#158]
Greetings,

Could you please let me know if it is possible to train DeepCell using images of a specific size (e.g., 256x256 pixels) and use it to predict segmentation on images of a different size (e.g., 2048x2048 pixels)?

Thank you

**Comment by willgraf** [comment]
Hi,

Yes, it is not an issue to train on one set of image sizes and predict on another.  There are some limitations on image size (mainly non-divisible image height/width can be an issue), but the image sizes you cite are definitely possible.

Train the model with the 256x256 images and save the weights only as an h5 file.  You can then create a NEW model with a different input shape (leaving the rest the same) and load the weights file.

Please see the [deepcell sample-mode notebook ](lhttps://github.com/vanvalenlab/deepcell-tf/blob/master/scripts/deepcell/Interior-Edge Segmentation 2D Sample Based.ipynb)for an example on how to do this.

**Comment by manugarciaquismondo** [comment]
Thank you, I have just tested it on our image set and it works fine. I will close the issue then.
