### ISSUE TITLE
Export model error

### ISSUE THREAD

**Issue by msschwartz21** [vanvalenlab/deepcell-tf#167]
https://github.com/vanvalenlab/deepcell-tf/blob/772a3ecd67da7294dc4c3f4383c3afcc588b5478/deepcell/utils/export_utils.py#L71

I think that the line of code above needs to be changed to `keras_model.output` in order to work correctly. I noticed this error while exporting the Retinanet model so it's possible that the issue was specific to me.

**Comment by willgraf** [comment]
This does indeed look like a bug!
