### ISSUE TITLE
object detection with P2 layer of RetinaNet with resnet50 backbone fails in tensorflow 1.11

### ISSUE THREAD

**Issue by nitzanrazin** [vanvalenlab/deepcell-tf#173]
object detection using the P2 layer of RetinaNet with resnet50 backbone fails in tensorflow 1.11.0 (when training on simple test data, the training runs but results are poor). This is fixed starting from tensorflow 1.12 (verified on 1.12.0, 1.14.0).

**Comment by willgraf** [comment]
This could be resolved by using the external library `keras-applications` instead of the built-in `tf.keras.applications`.  This would un-pin the models from the current tensorflow version.

Alternatively, we could just only support tfv1.12+
