### ISSUE TITLE
Loading pre-trained models on deepcell

### ISSUE THREAD

**Issue by manugarciaquismondo** [vanvalenlab/deepcell-tf#175]
Could you please let me know how to load pre-trained models on Deepcell? When I load a model using `model_from_json` from Tensorflow, I obtain an error saying that Keras could not find the given layers. I solved the issue by manually adding the layers used on Deepcell
```
model_from_json(loaded_model_json, {'ImageNormalization2D':ImageNormalization2D,
                                                           'GlorotUniform':glorot_uniform(),
                                                           'truncated_normal':truncated_normal,
                                                           'DilatedMaxPool2D':DilatedMaxPool2D,
                                                           'TensorProduct':TensorProduct,
                                                           'ReflectionPadding2D':ReflectionPadding2D})
```
Is there any manner to load Deepcell models without having to specify the used Deepcell layers one by one?

Thank you,

**Comment by willgraf** [comment]
We typically save and load models using the `model.save_weights` and `model.load_weights` functions.

For example, after training a model we can save its weights:

```
model_path = 'path/to/weights/file.h5'
model.fit_generator(...)
model.save_weights(model_path)
```

We can then load that model with a new input shape:

```
# Set up the prediction model
prediction_model = model_zoo.MaskRCNN(
    backbone=backbone,
    use_imagenet=False,
    panoptic=True,
    num_semantic_heads=2,
    num_semantic_classes=[4, 4],
    input_shape=(None, None, X_train.shape[-1]),  # general input size
    num_classes=num_classes,
    backbone_levels=backbone_levels,
    pyramid_levels=pyramid_levels,
    anchor_params=anchor_params)

prediction_model.load_weights(model_path)
```

**Comment by willgraf** [comment]
And to answer your question specifically, when using `model_from_json` you WILL need to directly add in each custom object each time, since TensorFlow is not aware of the deepcell specific Layers.
