### ISSUE TITLE
Metrics JSON export not functional

### ISSUE THREAD

**Issue by MekWarrior** [vanvalenlab/deepcell-tf#176]
The Metrics.save_to_json() function is incomplete. It doesn't return all of the summary statistics and it reports incorrect values for pixel-based measurements (ie. Jaccard Index).

**Comment by willgraf** [comment]
Looking into this a bit, it looks like `save_to_json` only adds metadata to the metrics passed to it, and saves a JSON file.

What behavior are you expecting?  This may just be that the data you passed to `save_to_json` was incorrect to begin with.

**Comment by willgraf** [comment]
Closing this as the metrics will now live in the deepcell-toolbox.

Closing in favor of vanvalenlab/deepcell-toolbox#27
