### ISSUE TITLE
running deepcell on GPUs - list of tested combinations of tensorflow and GPU

### ISSUE THREAD

**Issue by nitzanrazin** [vanvalenlab/deepcell-tf#183]
tensorflow 1.11.0, 1.12.0:
deepcell **successfully runs** on both GeForce GTX 1080 Ti and Tesla V100-DGXS-16GB GPUs

tensorflow 1.14.0:
- requires CUDA 10, which **requires Tesla GPUs** - thus doesn't run on GeForce GTX 1080 Ti GPUs
- **fails to run on the GPUs** of a server with Tesla V100-DGXS-16GB GPUs (runs on 0 GPUs when try to run on GPU)

**Comment by willgraf** [comment]
[Here](https://www.tensorflow.org/install/source#tested_build_configurations) is an up to date list of tensorflow version compatibilities.

**Comment by willgraf** [comment]
Because the main compatibility issue is TensorFlow rather than deepcell, I'm going to close this issue.
