### ISSUE TITLE
RetinaMask Notebook

### ISSUE THREAD

**Issue by vanvalen** [vanvalenlab/deepcell-tf#191]
Need a notebook showing RetinaMask/MaskRCNN training

**Comment by willgraf** [comment]
There are a few notebooks [here](https://github.com/vanvalenlab/deepcell-tf/tree/master/scripts/feature_pyramids) which show RetinaNet training (just bounding boxes), MaskRCNN training, and full panoptic training with multiple semantic heads.

Is this what you were looking for? Or is there another type of notebook I can add?
