### ISSUE TITLE
Predicting constant value across entire image with 2D sample-mode pixelwise

### ISSUE THREAD

**Issue by ngreenwald** [vanvalenlab/deepcell-tf#207]
I ran into the following issue while training a sample-based 2D network with the deepcell (pixel) data transformation. 

For a very particular set of parameters, the resulting trained network would predict the same value across the entire image.  It was reproducible across multiple distinct training runs. I'm not sure if it's a bad local minima, an error in my training data generation, or a bug in the model architecture. 

This constant prediction error cropped up in the model savepoints across all epochs during training.

Using the exact same network parameters, a watershed network produced a working network without any issues. 

By tweaking the max_class_examples parameter, I found that the error only appeared when >400k examples were selected, corresponding to 80k examples per image.

**Comment by willgraf** [comment]
I'm going to close this issue since it's 18 months old and it does not seem to have come up again.

Please re-open it if the issue arises again.
