### ISSUE TITLE
Calculate mAP in metrics

### ISSUE THREAD

**Issue by ngreenwald** [vanvalenlab/deepcell-tf#223]
https://github.com/vanvalenlab/deepcell-tf/blob/09a7b10cbd044eaec80c9466f349873fe5455257/deepcell/utils/retinanet_anchor_utils.py#L773

Currently mAP is calculated during retinanet training, but the metrics package itself doesn't calculate this (from what I can tell), meaning its tough to figure out how its doing on test data compared to training callbacks

**Comment by willgraf** [comment]
Closing this as the metrics will now live in the deepcell-toolbox.

Closing in favor of vanvalenlab/deepcell-toolbox#26
