### ISSUE TITLE
Metrics should be updated with bbox overlap code

### ISSUE THREAD

**Issue by MekWarrior** [vanvalenlab/deepcell-tf#232]
Currently, the metrics package calculates an IOU for every object. This should be changed to only calculate for objects with overlapping bboxes.

**Comment by willgraf** [comment]
This was originally in the `enhance_retinanet` branch, which was gutted and split into several other branches, including [metrics-bbox](https://github.com/vanvalenlab/deepcell-tf/tree/metrics-bbox).

I believe the metrics code is non-functional but is a strong start to resolving this.

**Comment by willgraf** [comment]
Fixed by #251
