### ISSUE TITLE
Include tensorflow probability dependency

### ISSUE THREAD

**Issue by vanvalen** [vanvalenlab/deepcell-tf#252]
It would be nice to have TFP included in the deepcell distribution. The line
RUN sed -i "/tensorflow/d" /opt/deepcell-tf/requirements.txt && \
prevents us from adding tensorflow probability to the requirements.txt file.

The other problem is that TFP requires pinning the TF version to 1.15.0rc1

**Comment by willgraf** [comment]
This is trivial now that we have migrated to TensorFlow 2.3.1. Installing `tensorflow-probabilty` in both the Docker container as well as a local environment should be a simple `pip install tensorflow-probability`.

I'm going to close this issue as there is not currently any code that uses TFP, but there is no problem installing and using TFP alongside deepcell. Once we have code that uses TFP it can be easily added to `setup.py` and `requirements.txt` as a depenency.
