### ISSUE TITLE
ISBI-formatted lineage .txt file should not allow non-contiguous parents

### ISSUE THREAD

**Issue by MekWarrior** [vanvalenlab/deepcell-tf#264]
There are rare cases where the translation from DeepCell lineage to an ISBI-formatted .txt file fails to correctly separate parents from daughters. In the ISBI format, each cell that leaves the frame is treated as a new cell when it re-enters the frame (new ID and track). Normally this is handled correctly, however, there are cases where a cell leaves the frame, divides off screen, and this new daughter enters the frame later. DeepCell tracking correctly identifies this event. But the translation function incorrectly allows this daughter cell to retain that information (it should be treated as a new cell/track with no parent information).

The translation should be amended to account for this edge case. Line 47 of code block 10 in the "Tracking Example with Benchmarking" could include a check as to whether the parent exists in the previous frame and, if not, do not assign/print a value for parent label.

**Comment by willgraf** [comment]
This is resolved in `deepcell-tracking>=0.2.4`.  This dependency will be updated in #267 which will resolve this issue.
