### ISSUE TITLE
load_training_data silently skips image folders without y labels

### ISSUE THREAD

**Issue by ngreenwald** [vanvalenlab/deepcell-tf#270]
https://github.com/vanvalenlab/deepcell-tf/blob/78bdf9b4ff40aec92b7cd5da54f14696267fcb36/deepcell/utils/data_utils.py#L613

The current implementation of load_training_data doesn't warn the user if there are directories missing channels or y labels, and instead just skips them. 

Do you frequently have datasets with a non-trivial number of missing labels/channels, and so generating a warning message for each would be overwhelming?

If so, I think adding a Verbose=True option which reports any missing files would be quite helpful. I'm happy to add this in, just wanted to check first to see if there was a reason you hadn't set this as the default behavior.

**Comment by willgraf** [comment]
The `load_training_data` in deepcell are somewhat of a vestige.  I believe the [deepcell-toolbox](https://github.com/vanvalenlab/deepcell-toolbox) is where these functions will live from now on.

We do not use this function much anymore, they were specifically designed for the edge/interior feature labeled data formatting. If there was a reason for skipping files silently, I do not know what it was.

I think there are myriad ways to improve these functions and we are open to any/all ideas.

**Comment by ngreenwald** [comment]
Got it, that makes sense. I'm also doing most of my data manipulation beforehand in our MIBI pipeline, but I had kept this one last part in deepcell. I'l go ahead and swap it into the MIBI pipeline. 

I think the best longterm plan is probably to have the data be formatted beforehand, especially once we start supporting multiple channels. That way it'll already come annotated with designated labels, and can be reordered appropriately, rather than relying on the alphabetical ordering I currently use. 

Once we reformat deepcell-toolbox for mibi data we can revisit this, probably doesn't make sense to invest significant time reworking it before that.
