### ISSUE TITLE
Metrics should report inference speed

### ISSUE THREAD

**Issue by vanvalen** [vanvalenlab/deepcell-tf#317]
**Is your feature request related to a problem? Please describe.**
The metrics package should take in a model and data. It should then run the model on the data, compute performance metrics and also report the inference speed. 

**Describe the solution you'd like**
It would be nice if the metrics suite built a report card for a model.

**Describe alternatives you've considered**
A separate function for benchmarking inference speed  would be an alternative.

**Additional context**
None

**Comment by willgraf** [comment]
Closing this as the metrics will now live in the deepcell-toolbox.

Closing in favor of vanvalenlab/deepcell-toolbox#26
