### ISSUE TITLE
Tracker on detections

### ISSUE THREAD

**Issue by samreenanjum** [vanvalenlab/deepcell-tf#323]
Hi,
Can I run your tracker on pre-computed bounding boxes? If so, could you please provide guidance on how to do so? Thank you!

**Comment by MekWarrior** [comment]
DeepCell.Tracking is meant for use with segmentation masks. As such, it uses regionprops from the skimage package. So it will need several modifications to work bounding boxes. 

You could either use DeepCell.org to segment these images (thereby providing the requisite masks), or you could apply some other method to pre-process the bounding boxes you have. 

Please refer to our DeepCell.Tracking repo (https://github.com/vanvalenlab/deepcell-tracking) for more information on how the tracking algorithm uses these parameters.

**Comment by samreenanjum** [comment]
Thanks for the clarification!
