### ISSUE TITLE
Error using deepcell.org segment prediction

### ISSUE THREAD

**Issue by samreenanjum** [vanvalenlab/deepcell-tf#325]
Hi, 
I'm trying to use deepcell.org to segment my image sequence, however, I run into the following error while testing with one image of shape 320*400: 
Job Failed: Traceback (most recent call last): File "/usr/src/app/redis_consumer/consumers/base_consumer.py", line 187, in consume status = self._consume(redis_hash) File "/usr/src/app/redis_consumer/consumers/image_consumer.py", line 251, in _consume label = self.detect_label(image) File "/usr/src/app/redis_consumer/consumers/image_consumer.py", line 144, in detect_label untile=False) File "/usr/src/app/redis_consumer/consumers/base_consumer.py", line 478, in predict tuple(model_shape))) ValueError: Image of shape (320, 400, 4, 1) is incompatible with model LabelDetection:1 with input shape (-1, 128, 128, 1)

Could you please help resolve this error? 

Thank you very much!

**Comment by willgraf** [comment]
We are currently in the process of upgrading the deepcell.org backend. I'll comment here when it is resolved.

**Comment by willgraf** [comment]
Also, it looks like the input shape of the image is `(320, 400, 4, 1)`. That seems like a pretty weird shape (rank 4?). What is the data type? Is this a .tiff image?

**Comment by samreenanjum** [comment]
Thank you for your response. I tried both with .jpg file and .tiff files extracted from a live-cell imaging video using ffmpeg. 

When I run the .jpg file, I get the following error instead:

**Comment by samreenanjum** [comment]
An update: I tested with tiff with 3 channels as well, and run into the same error as in the first comment:
ValueError: Image of shape (320, 400, 3, 1) is incompatible with model LabelDetection:1 with input shape (-1, 128, 128, 1)

**Comment by willgraf** [comment]
Our models have been trained for a single channel. I think currently tiff files are automatically expanded for the channel dimension. Can you try submitting an image of shape `(320, 400)`?

**Comment by samreenanjum** [comment]
That works! Thank you very much for your help!

Could you please clarify the acceptable file types for the Tracking module on the website? I was trying to run "Tracking" with the sample 3D tiff file on deepcell.org (3T3_nuc_example_256.tif) but received the following error: 

Job Failed: Traceback (most recent call last): File "/usr/src/app/redis_consumer/consumers.py", line 191, in consume status = self._consume(redis_hash) File "/usr/src/app/redis_consumer/consumers.py", line 1245, in _consume data = self._load_data(redis_hash, tempdir, fname) File "/usr/src/app/redis_consumer/consumers.py", line 1196, in _load_data hash_to_frame[segment_hash], reason)) RuntimeError: Tracking failed during segmentation on frame 0. Segmentation Error: Traceback (most recent call last): File "/usr/src/app/redis_consumer/consumers/base_consumer.py", line 187, in consume status = self._consume(redis_hash) File "/usr/src/app/redis_consumer/consumers/image_consumer.py", line 267, in _consume image = self.predict(image, model_name, model_version) File "/usr/src/app/redis_consumer/consumers/base_consumer.py", line 467, in predict model_metadata = self.get_model_metadata(model_name, model_version) File "/usr/src/app/redis_consumer/consumers/base_consumer.py", line 321, in get_model_metadata model_metadata = client.get_model_metadata() File "/usr/src/app/redis_consumer/grpc_clients.py", line 206, in get_model_metadata response = self._retry_grpc(request, request_timeout) File "/usr/src/app/redis_consumer/grpc_clients.py", line 155, in _retry_grpc raise err File "/usr/src/app/redis_consumer/grpc_clients.py", line 123, in _retry_grpc response = api_call(request, timeout=request_timeout) File "/usr/local/lib/python3.6/site-packages/grpc/_channel.py", line 565, in __call__ return _end_unary_response_blocking(state, call, False, None) File "/usr/local/lib/python3.6/site-packages/grpc/_channel.py", line 467, in _end_unary_response_blocking raise _Rendezvous(state, None, None, deadline) grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with: status = StatusCode.NOT_FOUND details = "Servable not found for request: Specific(panoptic, 3)" debug_error_string = "{"created":"@1584154199.463885899","description":"Error received from peer ipv4:10.3.247.112:8500","file":"src/core/lib/surface/call.cc","file_line":1052,"grpc_message":"Servable not found for request: Specific(panoptic, 3)","grpc_status":5}" >

**Comment by willgraf** [comment]
This should be resolved. As I mentioned we are currently in the process of migrating our deployed models to the Watershed Regression models.  I think it should be good to go now.

**Comment by samreenanjum** [comment]
yes, thank you for resolving the error! It works now.

A follow-up question regarding segmentation: 
When I run the NuclearSegmentationModel model with pretrained weights using your api:
from deepcell.applications.nuclear_segmentation import NuclearSegmentationModel
model = NuclearSegmentationModel(input_shape=tuple(X_test.shape[1:]), backbone='resnet50', use_pretrained_weights=True)

I get the following error:
ValueError: You are trying to load a weight file containing 174 layers into a model with 177 layers.

Is this also related to the migration?

**Comment by willgraf** [comment]
Yes, I believe that is also due to the migration.

**Comment by willgraf** [comment]
Closing this as it is more a [kiosk](github.com/vanvalenlab/kiosk-console) problem, ultimately related to a stale deployment for deepcell.org.
