### ISSUE TITLE
The README needs to be update

### ISSUE THREAD

**Issue by MekWarrior** [vanvalenlab/deepcell-tf#334]
**Describe the bug**
The README is not clear enough for new users and some of the commands do not apply to the latest versions of Nvidia Docker. 

**The lines that are particularly concerning are:**

The fastest way to get started with DeepCell is to run the docker image:

nvidia-docker run -it --rm -p 8888:8888 vanvalenlab/deepcell-tf:0.4.0-gpu

**Comment by MekWarrior** [comment]
The tag here should also be changed:

Run the new docker image

# NV_GPU refers to the specific GPU to run DeepCell on, and is not required

NV_GPU='0' nvidia-docker run -it \
-p 8888:8888 \
$USER/deepcell-tf:0.4.0-gpu

**Comment by epao111** [comment]
The readme needed more information on what parts of code to change to make it work for new users. This includes changing the port number and what directories can be changed/need to be changed. 

ctrl + p and ctrl+ q did not exit docker for me. Docker image was built on a windows machine and ssh using putty. I was able to exit by pressing a combination of ctrl + p + q multiple times.
