### ISSUE TITLE
IOU threshold in metrics package results in merges being misclassified as misses

### ISSUE THREAD

**Issue by ngreenwald** [vanvalenlab/deepcell-tf#339]
The current metrics package uses IOU as a threshold for determining when a predicted cell and a true cell should be linked together. However, if one cell is much smaller than the other cell, even if the the small one is completely contained within the larger cell, the IOU will be quite small. 

For example, here's a test function Morgan wrote that generates 3 ground truth cells:
![image](https://user-images.githubusercontent.com/13770365/78186734-18159880-7422-11ea-9108-9fec333a9fcf.png)

It then generates an erroneous prediction of two of the cells merged together:
![image](https://user-images.githubusercontent.com/13770365/78186755-22379700-7422-11ea-9f0c-790744d6eb7d.png)

However, because the aqua cell in the top left of the true labels is quite small, the IOU between it and the yellow cell in the predicted cell is only 0.06. Thus, it gets discarded as a linked cell for the large cell. 

This means that during assignment, the large yellow predicted cell is only linked with the large yellow true cell. Therefore, the yellow-yellow link is counted as a correct prediction, the green-green link is counted a correct prediction, and the aqua cell is counted as "missed" in the predicted labels.

Morgan and I have been discussing possible ways to get around this. 

One way to address this would be to lower the threshold for determining when two cells are linked. However, this will result in false positives when two large cells happen to overlap each other. 

Another way to address this would be to use a combination of IOU and something else to construct the matrix. For example, you could compute the % of cell1 that is within cell2 for all cells with a non-zero IOU, and then take the max of that value and IOU. In this case, if 100% (or even 40%) of a small cell was contained within a large cell, instead of an IOU of .06 it would get bumped to 0.4, which would be well clear of the threshold. 

If you all have other ideas for ways we could address this would love to hear it!

**Comment by ngreenwald** [comment]
Okay, there's another problem. Even if we fix the above problem and boost the IOU of the small cells with the large cell so they don't get dropped, it doesn't fix the issue. 

The reason is that the true yellow cell and predicted yellow cell have a very high IOU. So during linear assignment, they get flagged as a match. This means the predicted yellow cell and true yellow cell get removed from subsequent graph assignment. 

In the above yellow scenario, the two yellow cells have an IOU of 0.9. I don't think we want to raise the threshold for a direct match above that level, as plenty of true hits will be around ~85% concordance, which is definitely good enough. @msschwartz21, any thoughts?

The hackiest idea I had was that when we're modifying the iou matrix, if we detect a cell with very high % included in another cell, and very low IOU, we penalize the IOUs of the partner cell across all columns to make sure it doesn't pass threshold

**Comment by vanvalen** [comment]
I think the behavior as written is correct.

**Comment by ngreenwald** [comment]
I suppose it comes down to what's the difference between a miss and a merge. 

As it currently stands, if a small and a large cell get combined together, it gets recorded as an accurate segmentation of the large cell and a miss of the small cell, rather than a merge of the large and small cell.
