### ISSUE TITLE
Add support for multiple labels for same image

### ISSUE THREAD

**Issue by ngreenwald** [vanvalenlab/deepcell-tf#343]
**Is your feature request related to a problem? Please describe.**
Currently to make predictions based on different labels of the same image, separate models need to be trained for each label. 

**Describe the solution you'd like**
It would be faster, and potentially lead to more expressive models, to supply multiple labels to a single model and have the same model make multiple predictions

**Describe alternatives you've considered**
Training separate models for each task. Works fine but is less elegant/extensible.

**Comment by willgraf** [comment]
Closed by #344
