### ISSUE TITLE
Panopticnet models don't build with non-square inputs

### ISSUE THREAD

**Issue by ngreenwald** [vanvalenlab/deepcell-tf#368]
**Describe the bug**
When trying to create a panopticnet an operand broadcast error gets thrown

**To Reproduce**
Try and run the deep watershed example notebook. 

**Screenshots**
![image](https://user-images.githubusercontent.com/13770365/80163591-7817de80-858b-11ea-85fd-b6ba8194ae4c.png)

**Additional context**
I didn't notice this earlier because it only gets thrown in particular circumstances. 

- if the input image crop is square it doesn't throw an error (this is how it slipped past the [test suite](https://github.com/vanvalenlab/deepcell-tf/blob/master/deepcell/model_zoo/panopticnet_test.py#L83): 
- If the input dimensions are sufficiently small (errors on 216x256, not 28x30)

Looks like it was introduced in #352

**Comment by vanvalen** [comment]
The image sizes for panopticnets are supposed to be powers of two. Perhaps we should have a error message appear.

**Comment by ngreenwald** [comment]
Got it. The current example notebook uses the HeLa dataset that's 216x256.
Should we change to a different dataset?

**Comment by willgraf** [comment]
Maybe we could just reshape it to 128x128?
