### ISSUE TITLE
Docker image to integrate into a pipeline

### ISSUE THREAD

**Issue by ngreenwald** [vanvalenlab/deepcell-tf#372]
**Is your feature request related to a problem? Please describe.**
A couple of groups have reached out to me with interest in using the multiplexed model as part of a larger image processing pipeline, as part of something like QuPath or Nextflow. I think the current setup of a jupyter notebook-based docker image is not super conducive to that. 

**Describe the solution you'd like**
I know that many of these pipelines can accept appropriately configured docker images that serve as one piece. How much work would it be to create a deepcell-tf image that would be compatible with some of these microscopy analysis pipelines? It wouldn't have to support training in any capacity, just inference of an existing application object.

**Comment by willgraf** [comment]
It does look like [NextFlow supports using docker containers in a pipeline](https://www.nextflow.io/docs/latest/docker.html).

**Comment by ngreenwald** [comment]
That's great. Looks like maybe all that's needed is copying the relevant code from the example applications notebook into a python script that they call, specifying with our container? And giving them a dockerfile that doesn't start up a jupyter notebook?

**Comment by willgraf** [comment]
The [deepcell-applications](https://github.com/vanvalenlab/deepcell-applications/) repository has been created for this.

Currently, it just has an example script using the deepcell `Applications`, but eventually, all of the applications will be migrated there.
