### ISSUE TITLE
Scale detection model in applications is broken

### ISSUE THREAD

**Issue by vanvalen** [vanvalenlab/deepcell-tf#377]
**Describe the bug**
Returns the following error: URL fetch failure on https://deepcell-data.s3-us-west-1.amazonaws.com/model-weights/ScaleDetectionModel_mobilenetv2.h5: 403 -- Forbidden

**To Reproduce**
Instantiate scale detection model

**Comment by willgraf** [comment]
Resolved. The newest h5 file had was missing the `"Model"` in the filename. This file was renamed in S3 to match the rest, and the issue is resolved.

The hashes also need to be updated, which will happen in #380
