### ISSUE TITLE
Help installing 

### ISSUE THREAD

**Issue by Sum02dean** [vanvalenlab/deepcell-tf#396]
I am working with an organization that doesn't allow me super user access, which is required for docker-gpu installation. Is there an alternative way to run this via a standard python environment? When attempting this, I seem to get many conflicts. 

Kind regards, 

Dean

**Comment by willgraf** [comment]
Docker is the recommended way to use deepcell.

However, you can install both deepcell and its dependencies via with `pip` by using the `Dockerfile` as a guide. 

```
cd /path/to/deepcell-tf
pip install -r requirements.txt
pip install .
python setup.py build_ext --inplace
```

I also think you will need to change the `tensorflow` requirement to `tensorflow-gpu` if you're planning to run on a GPU.

**Comment by Sum02dean** [comment]
Thank you for the quick reply. I will try as suggested shortly. 
many thanks!

**Comment by Sum02dean** [comment]
Hi @willgraf 
I wanted to let you know that the steps you outlined worked fine.

Many thanks, 

Dean

**Comment by willgraf** [comment]
Awesome! Glad to hear you got it up and running.
