### ISSUE TITLE
readthedocs inconsistency and retinaMask example  function

### ISSUE THREAD

**Issue by NikoNegima** [vanvalenlab/deepcell-tf#400]
Hi, some questions and info about this amazing library.

In the example with the retinaMask model (found in the notebooks/training folder), the function **get_anchor_params** from the _utils.retinanet_anchor_utils_  package its not found. All old examples based in this example don't work anymore because of this.

In the readthedocs page (_deepcell.readthedocs.io/en/master/_) this function exists, but using the help command with the package, there are not information about the **get_anchor_params**, or any function goes generate the aurgements necessary from the creation of a retinaMask zoo_model. Are some alternatives?

Thanks for everything!

**Comment by willgraf** [comment]
I'm not aware of any `get_anchor_params` functions. However, there are 2 functions that are similarly named (but do not do the same things):

- `retinanet_anchor_utils.get_anchor_parameters` (generate some parameters based on your data)
- `retinanet_anchor_utils.generate_anchor_params` (internal function used in model creation)

I just ran through the `RetinaMask` notebook using the `vanvalenlab/deepcell-tf:0.5.0-gpu` docker image and had no issue. Can you help me reproduce the problem?

**Comment by NikoNegima** [comment]
Yeah, i found the problem, I using the 0.4.0-gpu docker image, so was a version problem! Thanks for the help. 

As a annotation, the readme.md in the **Getting Started** section, indicates the image docker is 0.4.0-gpu, and the segmentation tutorial links go to a error (Maze found).

**Comment by willgraf** [comment]
Thanks, good catch. I've just opened a PR to fix the README.
