### ISSUE TITLE
Weights for MultiplexApplication redownload

### ISSUE THREAD

**Issue by vanvalen** [vanvalenlab/deepcell-tf#411]
**Describe the bug**
Weights for the multiplex application are redownloaded due to an incorrect hash. This may be due to the hash value being incorrect.

**Expected behavior**
Model weights should download once, and not be re-downloaded if the application object is re-instantiated.

**Desktop (please complete the following information):**
Ubuntu 16.04

**Comment by ngreenwald** [comment]
I think you're right, I didn't update the hash when I put the new model
weights in. You can still run it, correct? It just updates more than needed?
If so I'll fix the hash when I put the newest version in. If it doesn't run
I can patch it now.
