### ISSUE TITLE
libGL error with latest version of deepcell-toolbox

### ISSUE THREAD

**Issue by vanvalen** [vanvalenlab/deepcell-tf#420]
**Describe the bug**
ImportError: libGL.so.1: cannot open shared object file: No such file or directory

**To Reproduce**
Bug appeared when forcing deepcell-toolbox installation to be version 0.6.1

**Expected behavior**
Expected bug to not be present

**Additional context**
Changing Dockerfile to the following fixed the error

# System maintenance
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    python3-tk \
    libsm6 \
    libgl1-mesa-dev && \
    rm -rf /var/lib/apt/lists/* && \
    /usr/local/bin/pip install --upgrade pip

**Comment by ngreenwald** [comment]
Just updated and got the same error

**Comment by willgraf** [comment]
I believe this issue is fixed by #423
