### ISSUE TITLE
Scale detection model training is hard-coded to current patch size

### ISSUE THREAD

**Issue by ngreenwald** [vanvalenlab/deepcell-tf#421]
**Describe the bug**
The current architecture for the scale detection model makes assumptions about the shape of the input data. Specifically, it is optimized for patches of 216x216. If larger patches (e.g. 256x256, 512x512) are used, the model can't train

**To Reproduce**
Attempt to use current jupyter notebook to train model on 256x256 data

**Screenshots**
Here's the last few layers of the model initialized with 256x256 data:
![image](https://user-images.githubusercontent.com/13770365/89842708-57b86380-db2b-11ea-8a9a-e4099269a195.png)

Here's what those layers look like in the example notebook created with 216x216 data:
![image](https://user-images.githubusercontent.com/13770365/89842740-6dc62400-db2b-11ea-9647-57b109cdb0b2.png)

Here's the error message: 
![image](https://user-images.githubusercontent.com/13770365/89842780-85051180-db2b-11ea-8ca0-946914f084cd.png)

**Comment by willgraf** [comment]
I retrained this using smaller patches (128, 128) with TensorFlow 2.3.1 and had no issues. However, I did not try to go larger.

**Comment by ngreenwald** [comment]
Yeah, large was the issue. I think there's insufficient maxpooling to get to an output of size 1for larger images
