### ISSUE TITLE
Keyword Argument Compartment for Method Predict (Multiplex Seg.) Error

### ISSUE THREAD

**Issue by saahuja** [vanvalenlab/deepcell-tf#427]
**Describe the bug**
When using the method predict for the multiplex segmentation application, the keyword argument compartment is not recognized. 

**To Reproduce**
1. Run Multiplex Application Notebook up until second to last cell
2. See error

**Screenshots**

![Capture](https://user-images.githubusercontent.com/22031143/91625426-0e09ae80-e95c-11ea-9c2d-19c016500e65.PNG)

**Desktop (please complete the following information):**
 - OS:  Ubuntu
 - Version 20.04
 - Python Version 3.6.7

**Comment by ngreenwald** [comment]
When was the last time that you rebuilt the docker image/pulled from master? This works for me off of the master branch, and this functionality was added in the last month or two. It's possible you have an old version that doesn't support this.

**Comment by saahuja** [comment]
Thank you. Turns out it was an older version works now.
