### ISSUE TITLE
Problems with .npz file and train_model_retinanet with a RetinaMask model.

### ISSUE THREAD

**Issue by NikoNegima** [vanvalenlab/deepcell-tf#432]
**Describe the bug**
Training a segmentation model using a own dataset, based on the examples [RetinaNet](https://github.com/vanvalenlab/deepcell-tf/blob/21a1d0c979652ff7f38bb665bb1526bcd0bb34ea/notebooks/training/retinanets/RetinaNet.ipynb) and [RetinaMask](https://github.com/vanvalenlab/deepcell-tf/blob/21a1d0c979652ff7f38bb665bb1526bcd0bb34ea/notebooks/training/retinanets/RetinaMask.ipynb) of the notebooks/training/retinanets generates two ValueErrors depending on the function to create the npz file required to the model . If i use the method of deepcell 0.5.0: *make_training_data* to create the fail, and execute the training of the model, i get a:

    "ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters." 

If i train the model with a numpy method, *np.savez_compressed*, with two npy, X for the images and y for the masks. i get a:

    ValueError: The name "anchors_0" is used 2 times in the model. All layer names should be unique.

**To Reproduce**

With this tree dir.

    data/img/Dataset
    │ ├── gs_images
    │ ├── gs_images
    │ │   ├── image0.jpg
    │ │   (...)
    │ │   ├── image20.jpg
    │ ├── Head-Masks
    │ │   ├── image0-mask1.jpg
    │ │   (...)
    │ │   ├── image20-mask1.jpg

The dataset is composed of 19 grayscale images of dimensions 780x580, read with PIL.Image in the jupyter notebook.
**First error:**
Calling the method "make_training_data_2d" to create the .npz file in this format. 

    imgs_dir = os.listdir('/data/img/Dataset/gs_images/')
 
    mask_dir = os.listdir('/data/img/Dataset/Head-Masks/')
    
    make_training_data_2d(direc_name="/data/img/",
                         file_name_save="/data/dataset_w_trainingdata2d",
                         training_direcs=["Dataset/"],
                         raw_image_direc="gs_images/",
                         annotation_direc="Head-Masks/",
                         channel_names=imgs_dir,
                         annotation_name=mask_dir,
                         reshape_size=None)

When the method *train_model_retinanet* is executed, i have this output 

    ---------------------------------------------------------------------------
    ValueError                                Traceback (most recent call last)
    <ipython-input-15-60e6dba3008b> in <module>
     27     flip=True,
     28     shear=False,
    ---> 29 zoom_range=(0.9, 1.1))
    (...)
    ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The *dataset_w_trainingdata2d.npz* file looks like this:
![enter image description here](https://i.imgur.com/W0ZuUgG.png)
**Second Error:**
Using the same tree dir, i create a .npz file with:

      path_imgs = "/data/img/Dataset/gs_images/*.jpg"
      path_mask = "/data/img/Dataset/Head-Masks/*.jpg"
      X = ([np.array(Image.open(file).convert('L')) for  file  in glob.glob(path_imgs)])
      y = ([np.array(Image.open(file).convert('L')) for  file  in glob.glob(path_mask)])
      X = np.reshape(X,(19,580,780,1)) #Format of Hela_S3.npz
      y = np.reshape(y,(19,580,780,1))
      np.savez_compressed('/data/datasetgs_img_savez' X=X, y=y).

The *datasetgs_img_savez.npz* file looks likes this:
![enter image description here](https://i.imgur.com/rfzkHGz.png)

Using this .npz file, when the method *train_model_retinanet*, the output is:

    X_train shape: (17, 580, 780, 1)
    y_train shape: (17, 580, 780, 1)
    X_test shape: (2, 580, 780, 1)
    y_test shape: (2, 580, 780, 1)
    Output Shape: (None, 100, None)
    Number of Classes: None
    Training on 1 GPUs
    
    ---------------------------------------------------------------------------
    ValueError                                Traceback (most recent call last)
    (...)
    ValueError: The name "anchors_0" is used 2 times in the model. All layer names should be unique.
    
   For this error, i need to change the names of some layers: 

> anchors_X (where X is all integers from 0 to 6),  anchors (Concatenate)
> boxes (RegressBoxes)
>  clipped_boxes (ClipBoxes) 
>  filtered_detections (FilterDetector)

<sub>[*model.summary() output](https://pastebin.com/izd8K50N) </sub>
Now, if the function *train_model_retinanet* is executed, the output is:

    X_train shape: (17, 580, 780, 1)
    y_train shape: (17, 580, 780, 1)
    X_test shape: (2, 580, 780, 1)
    y_test shape: (2, 580, 780, 1)
    Output Shape: (None, 100, None)
    Number of Classes: None
    Training on 1 GPUs
    
    W0916 00:30:59.481801 140010808407872 training_utils.py:1101] Output masks missing from loss dictionary. We assume this was done on purpose. The fit and evaluate APIs will not be expecting any data to be passed to masks.
    W0916 00:30:59.482537 140010808407872 training_utils.py:1101] Output filtered_detections missing from loss dictionary. We assume this was done on purpose. The fit and evaluate APIs will not be expecting any data to be passed to filtered_detections.
    W0916 00:30:59.483144 140010808407872 training_utils.py:1101] Output filtered_detections_1 missing from loss dictionary. We assume this was done on purpose. The fit and evaluate APIs will not be expecting any data to be passed to filtered_detections_1.
    W0916 00:30:59.483712 140010808407872 training_utils.py:1101] Output filtered_detections_2 missing from loss dictionary. We assume this was done on purpose. The fit and evaluate APIs will not be expecting any data to be passed to filtered_detections_2.
    W0916 00:30:59.484195 140010808407872 training_utils.py:1101] Output mask_submodel missing from loss dictionary. We assume this was done on purpose. The fit and evaluate APIs will not be expecting any data to be passed to mask_submodel.
    
    Epoch 1/10
    
    ---------------------------------------------------------------------------
    ValueError                                Traceback (most recent call last)
    (...)
    ValueError: Variable <tf.Variable 'Variable:0' shape=(6, 4) dtype=float32> has `None` for gradient. Please make sure that all of your ops have a gradient defined (i.e. are differentiable). Common ops without gradient: K.argmax, K.round, K.eval.

 

**Expected behavior**
The Method train_model_retinanet starts training the model.

**Desktop (please complete the following information):**
 - OS: 	Manjaro Linux 20.1
  - Docker Version: Docker version 19.03.12-ce, build 48a66213fe
  - Docker Image: vanvalenlab/deepcell-tf:0.5.0-gpu
  - Python (Local Machine): 3.6.5

**Additional context**

A Panoptic Model based in the *[Nuclear Segmentation - DeepWatershed.ipynb](https://deepcell.readthedocs.io/en/master/notebooks/Training-Segmentation.html)* using the same dataset works without any problem.

The train_model_retinanet method has this params.

    from deepcell.training import train_model_retinanet
    
    model = train_model_retinanet(
        model=model,
        backbone=backbone,
        dataset=DATA_FILE,  # full path to npz file
        model_name=model_name,
        anchor_params=anchor_params,
        pyramid_levels=pyramid_levels,
        panoptic=False,
        sigma=3.0,
        alpha=0.25,
        gamma=2.0,
        weighted_average=True,
        score_threshold=0.01,
        iou_threshold=0.5,
        max_detections=100,
        test_size=0.1,
        seed=0,
        optimizer=optimizer,
        batch_size=batch_size,
        n_epoch=n_epoch,
        log_dir=LOG_DIR,
        model_dir=MODEL_DIR,
        lr_sched=lr_sched,
        rotation_range=180,
        flip=True,
        shear=False,
        zoom_range=(0.9, 1.1))

The *backbone_level, pyramid_level* andn *anchor_param* values are:

    backbone_level: ['C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7'] 
    pyramid_level: ['P1', 'P2', 'P3', 'P4', 'P5', 'P6', 'P7'] 
    anchor_param: <deepcell.utils.retinanet_anchor_utils.AnchorParameters object at 0x7f510dc230b8>

**Comment by willgraf** [comment]
There's a lot going on here so I will try to tackle a few issues one by one:

---

> "ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters." 

`make_training_data_2d` is inflexible and relies on a specific folder structure. It looks like you've worked around the first issue in this post, but I think the `ValueError` you saw was because of the `n_samples=1 + test_size=0.1`.  It cannot split a single sample up into train/test.

Ultimately, the `savez_compressed` output should be very similar to `make_training_data`.

---

> "ValueError: The name "anchors_0" is used 2 times in the model. All layer names should be unique."

Then, you hit an issue with duplicate named anchor layers. I'm not sure why we would end up with duplicated layers, could you elaborate on how you renamed them and moved past this error?

---

> "ValueError: Variable <tf.Variable 'Variable:0' shape=(6, 4) dtype=float32> has `None` for gradient. Please make sure that all of your ops have a gradient defined (i.e. are differentiable). Common ops without gradient: K.argmax, K.round, K.eval."

It looks like this error is due to the output shape of the model, `(None, 100, None)`. The last axis should be the number of classes the model is predicting. I have usually used a single class for "object", though if your needs require multiple classes they can be supported as well.

---

Finally, the `train_model` functions are opaque and hide a lot of the internal mechanisms. I suggest debugging the training by trying to copy/paste only the required bits of code from the `train_model` function.

**Comment by willgraf** [comment]
I'm going to close this due to inactivity. If you're still having issues please re-open it.
