### ISSUE TITLE
Assist user to choose the proper parameter **micron per pixel**

### ISSUE THREAD

**Issue by minhtran1309** [vanvalenlab/deepcell-tf#471]
I received the image from the collaborator who doesn't know much about technology and I don't know the conversion of a micron per pixel to predict the image. 

Say I have a ome tiff image of DAPI channel and want to run NuclearSegmentation using DeepCell pre-trained model. Yet I don't know what is the best model to use since the parameter `image_mpp` seems to affect the output significantly.
```
app = NuclearSegmentation()
cell_masked_img2 = app.predict(nuclei_images, image_mpp=0.65)
cell_masked_img = app.predict(nuclei_images, image_mpp=1.5)
```
and the result shown below. 
`image_mpp = 0.65`
![Screen Shot 2021-01-12 at 3 11 04 pm](https://user-images.githubusercontent.com/53423600/104272339-9d1cfa80-54e8-11eb-9ac8-d2fb4fc3eeaf.png)

`image_mpp = 1.5`
![Screen Shot 2021-01-12 at 3 11 51 pm](https://user-images.githubusercontent.com/53423600/104272349-a1491800-54e8-11eb-8d66-a1dff495dc1b.png)

**Comment by willgraf** [comment]
`image_mpp` represents the microns per pixel in the image. The current pre-trained Nuclear Segmentation model was trained on images with 0.65 microns per pixel, so if the input image has a different mpp value the image will be rescaled appropriately.

We are working on automatic resolution detection, but for best segmentation results I recommend asking the source of the images for the resolution.

**Comment by vanvalen** [comment]
For tissue data, you might want to try the multiplex model, passing in an image of 0's for the membrane/cytoplasm channel.

**Comment by minhtran1309** [comment]
Thanks, 

> For tissue data, you might want to try the multiplex model, passing in an image of 0's for the membrane/cytoplasm channel.

oh yea, that explains why the performance seems to improve when I use a batch of 2-channel images with the `MultiplexSegmentation()` model.

However, I realize that the results produced by myself are slightly different from the results produced by the web app. As shown in the figure below (the left figure was generated by MultiplexSegmentation() model (MultiplexSegmentation-6), and the right figure was generated by the web app). When I look at the number of cells that the model can segment, the left figure already has more cells than the right one. Yet, I think the one generated by the web app is more accurate.  Noted that the input images were the same.
<img width="1252" alt="Screen Shot 2021-01-13 at 10 57 29 am" src="https://user-images.githubusercontent.com/53423600/104392787-8fba4b80-558e-11eb-8cc9-312258461a86.png">
Is there any preprocessing step that I should do prior to predict the image? Thanks a lot.

**Comment by willgraf** [comment]
Apologies for the late follow-up! There are no preprocessing steps required, the model version in the `deepcell` package and the one deployed on deepcell.org were different (The webpage had an older model version up). This should now be rectified.

**Comment by willgraf** [comment]
Closing this issue as the immediate problem was resolved by using `MultiplexSegmentation` (now `Mesmer`), and there currently no good way to inform the user of the physical dimensions of their imaging subjects.
