### ISSUE TITLE
Dependencies versions constraints

### ISSUE THREAD

**Issue by plankter** [vanvalenlab/deepcell-tf#477]
Thank you for the great project!

It would be very helpful to update some dependencies or weaken their version pinning. For instance, there is a bug in `scikit-image` 0.16.2 (which is exactly the version supported by DeepCell: 'scikit-image>=0.14.1,<=0.16.2',) that has a serious impact on single-cell analysis, like calculation of cell centroids, etc: https://github.com/scikit-image/scikit-image/issues/4280.

It would be nice to have an updated version of `opencv-python-headless` as well (4.x is available for a long time).

Best regards,
Anton Rau

**Comment by willgraf** [comment]
Hi Anton,

You are right! `scikit-image` version restriction is far too limited. The next release will allow `scikit-image<0.17`, though there's breaking changes in .17+ that we cannot currently resolve.

I'm less familiar with the `opencv-python-headless` releases but will look into those as well.

**Comment by plankter** [comment]
Unfortunately, the next available version after 0.16.2 is 0.17.1 :(

**Comment by willgraf** [comment]
The new 0.8.4 release has unpinned the versions of `opencv-python-headless`.
