### ISSUE TITLE
"AbortedError: Could not create a descriptor for a softmax forward propagation primitive"

### ISSUE THREAD

**Issue by marc-vaisband** [vanvalenlab/deepcell-tf#509]
There seems to be something going on with TensorFlow that is breaking the app's predict functionality. The following block of code:

`from deepcell.applications import Mesmer`
`from deepcell.datasets import multiplex_tissue`
`((X_train, y_train),(X_test, y_test)) = multiplex_tissue.load_data()`
`app = Mesmer()`
`segmentation_predictions = app.predict(X_train, image_mpp=0.5)`

will currently fail with 

`AbortedError:  Operation received an exception:Status: 2, message: could not create a descriptor for a softmax forward propagation primitive, in file tensorflow/core/kernels/mkl/mkl_softmax_op.cc:306
	 [[node panopticnet/semantic_1/Softmax (defined at /home/marc/anaconda3/lib/python3.8/site-packages/deepcell/applications/application.py:340) ]] [Op:__inference_predict_function_38062]`

after a lengthy stack trace (appended)
[tensorflow_stacktrace.txt](https://github.com/vanvalenlab/deepcell-tf/files/6279754/tensorflow_stacktrace.txt)

 through various tensorflow scripts. This is with Tensorflow 2.4.1 and deepcell 0.9.0.

**Comment by willgraf** [comment]
Thanks for the post! Could you please include the Python version you are using as well as the `tensorflow` and `deepcell` versions?

A cursory Google search leads me to suspect that this could be related to the [Anaconda Python distribution](https://github.com/tensorflow/tensorflow/issues/23145).

**Comment by marc-vaisband** [comment]
@willgraf This is with `tensorflow 2.4.1`, `deepcell 0.9.0` and `python 3.8.2`. And it is indeed an Anaconda distribution.

**Comment by ngreenwald** [comment]
I would definitely recommend trying out the Docker installation, saves a lot of headache for these types of issues.

**Comment by willgraf** [comment]
Agreed. I'm inclined to think this is an issue with your local Anaconda setup and TensorFlow, and not a `deepcell` issue in particular.

Please try the Docker environment to see if this resolves your issue.

**Comment by marc-vaisband** [comment]
I'd actually already tried and failed to set up from the docker environment, but that's definitely a local issue. I'll see whether I can fix the Docker setup and if that resolves the issue

**Comment by willgraf** [comment]
I'm going to close this assuming the issue was resolved. Please re-open it if I am mistaken.
