### ISSUE TITLE
Error during training: input ran out of data

### ISSUE THREAD

**Issue by siyuh** [vanvalenlab/deepcell-tf#519]
Hi,

Thanks for your excellent work! I run the exemplary code here: https://deepcell.readthedocs.io/en/master/notebooks/Training-Tracking.html

With all the parameter the same, but I always get this error:

WARNING:tensorflow:Your input ran out of data; interrupting training. Make sure that your dataset or generator can generate at least `steps_per_epoch * epochs` batches (in this case, 9810.0 batches). You may need to use the repeat() function when building your dataset.

Would you please help to solve the issue? Thanks very much!

**Comment by willgraf** [comment]
I'm going to close this issue as a duplicate. If you continue to have problems, please follow up on issue #455.

Thanks!

**Comment by siyuh** [comment]
Thank you so much, this is very helpful!!
