### ISSUE TITLE
Pre-trained model file in the notebook for cell tracking is missing

### ISSUE THREAD

**Issue by Yiming0416** [vanvalenlab/deepcell-tf#522]
**Describe the bug**
In the notebook Tracking Example with Benchmarking.ipynb, in the section Import a Tracking Model to Use. The siamese_weights_file = 'tracking_model_seed1_tl9.h5' is not found.

Could you please let me know where can I get the pre-trained model file? Thanks

**Comment by willgraf** [comment]
Apologies for the late reply. I don't have the h5 file available for download but you can generate your own by training your own tracking model following the other tracking notebook.

**Comment by willgraf** [comment]
Closed by #506
