### ISSUE TITLE
Have problem on using trainned .h5 model to track cell

### ISSUE THREAD

**Issue by jizhouh** [vanvalenlab/deepcell-tf#523]
Hello,

I followed the [instruction](https://deepcell.readthedocs.io/en/master/notebooks/Training-Tracking.html) and finally got a h5 model for tracking cell. Then I had trouble on using it.

In order to track my own data, I found instructions on '[deepcell-tracking](https://git.sdut.me/vanvalenlab/deepcell-tracking/tree/master/deepcell_tracking)', and I tried to execute the following code

**tracker = CellTracker(X, y, model)**

However, when I tried to load model through this code

**model_path = '/path/to/file/tracking_model_seed1_tl9.h5'
model = model_zoo.siamese_model(
   input_shape=in_shape,
   neighborhood_scale_size=neighborhood_scale_size,
   features=features)
model = model.load_weights(model_path)**

It gave me an error said **ValueError: Unknown loss function: loss_function** when I tried **tracker.track_cells()**
Then I called **model.summary()**, it said **'NoneType' object has no attribute 'summary'**

Then I tried 

**model = tracking_model.load_weights(model_path)**    (where 'tracking_model' is the variable generated from the code in this [page](https://deepcell.readthedocs.io/en/master/notebooks/Training-Tracking.html)), and that code gave me the same error.

Therefore, I decided to ignore the problem on loading the model from .h5 file. Instead, I directly used 'tracking_model' generated before, executing the following code

**tracker = CellTracker(X, y, tracking_model)**

This time no error occurred, but the result was not I expected.
I put raw image stack as **X**, and segmented image stack as **y** (where the first image in segmented image stack is labeled, each cell being given an unique number, while the other are only segmented, and composed by 0 and 1). The result was the same as the input **y**, except the fact that 1 was changed to 2629 in the data. 

I did see the instruction said **'X and y are the time-sequence data and their corresponding segmentations (labels), respectively.'** But when I put segmented image stack (without the first image being labeled uniquely) as **y**, I received the same result as the input again.

I am pretty sure I messed up at some steps, could anyone help me please? Thanks a lot.

**Comment by willgraf** [comment]
> model_path = '/path/to/file/tracking_model_seed1_tl9.h5'
> model = model_zoo.siamese_model(
> input_shape=in_shape,
> neighborhood_scale_size=neighborhood_scale_size,
> features=features)
> model = model.load_weights(model_path)

I believe the problem is that `model.load_weights` does not return a value, so when you use `model = model.load_weights`, you are replacing `model` with `None`. However, I think that using `tracker = CellTracker(X, y, tracking_model)` should work.

> I put raw image stack as X, and segmented image stack as y (where the first image in segmented image stack is labeled, each cell being given an unique number, while the other are only segmented, and composed by 0 and 1).

The model expects each object in an image to have a different label. Please make sure that the objects in `y` are uniquely labeled in each image (there can be a cell with label 2 in every image, but only one per image). You can use [`skimage.measure.label`](https://scikit-image.org/docs/dev/api/skimage.measure.html#skimage.measure.label) to do this.

**Comment by jizhouh** [comment]
> > model_path = '/path/to/file/tracking_model_seed1_tl9.h5'
> > model = model_zoo.siamese_model(
> > input_shape=in_shape,
> > neighborhood_scale_size=neighborhood_scale_size,
> > features=features)
> > model = model.load_weights(model_path)
> 
> I believe the problem is that `model.load_weights` does not return a value, so when you use `model = model.load_weights`, you are replacing `model` with `None`. However, I think that using `tracker = CellTracker(X, y, tracking_model)` should work.
> 
> > I put raw image stack as X, and segmented image stack as y (where the first image in segmented image stack is labeled, each cell being given an unique number, while the other are only segmented, and composed by 0 and 1).
> 
> The model expects each object in an image to have a different label. Please make sure that the objects in `y` are uniquely labeled in each image (there can be a cell with label 2 in every image, but only one per image). You can use [`skimage.measure.label`](https://scikit-image.org/docs/dev/api/skimage.measure.html#skimage.measure.label) to do this.

Thanks a lot. I successfully load the model, but during the test, I met some other weird problems. 

Firstly, I tried to run code on **Jupyter notebook** invoked by **docker run --gpus '"device=0"' -it --rm**. Codes worked fine, but I encountered **GPU memory leak** during **training**. This problem did not occur when I run code on **Jupyter notebook** opened through **anaconda navigator**. Therefore I guess that was caused by installation problem.

Secondly, it seems like only CPU was used during **training and tracking**. I did have **"Training on 1 GPUs."** shown in my output, but as I monitored CPU and GPU, CPU usage achieved 100% periodically at all cores during training, while GPU usage was 2% at all time. Consequently, I spent extremely long time on running **tracker.track_cells()**, which took me about half hour to get it done (or memory leak error, which I will state below). As stated above, GPU was not used during tracking.

The last question was the motherboard memory leak. I did not have this problem when I post this question, but today I could not figure it out. I think there were two differences between the two days. Two days ago, my **y** data-set did not follow the rule, while today's was "correct"; also, two days ago I did not install nvidia-docker2, but today I have it on my system. More details, in the first 20 mins, the motherboard memory usage was around 8 GB (~50%), and soon the usage increased to 100% (around 10 seconds) and kernel died out. Note that the problem occurred on both of the ways I run Jupyter Notebooks.

Here is part of the info of my setting:

**Training set:
Dataset Statistics: 
Image data shape:  (2, 30, 300, 300, 1)
Number of lineages (should equal batch size):  2
Total number of unique tracks (cells)      -  244
Total number of divisions                  -  4
Average cell density (cells/100 sq pixels) -  0.1302222222222222
Average number of frames per track         -  28**

**Model summary:
Total params: 535,811
Trainable params: 532,995
Non-trainable params: 2,816**

**Test set:
X shape: (5, 2048, 2048, 1)
y shape: (5, 2048, 2048, 1)**

Note that it looks like there was not a significant time difference between the 5 frames data-set and a 30 frames data-set when I tried to track.

**Comment by jizhouh** [comment]
It seems like an data set error. 

The input labeled image that I successfully "tracked" was purely composed by 0 and 1, so I guess the algorithm only need to track one cell, meaning that it will not take computational power.

The input labeled image that I failed to track had 5000+ cells in one image (so in total 5000*5 cells, in five 2048*2048 images), so it makes sense to me that the motherboard memory was not enough.

Then I tried a smaller input labeled image, which has 100+ cells, with a size of 300*300, and a total of 30 images, and this time the algorithm worked.

Therefore, I believe if I use **docker run --gpus '"device=0"' -it --rm** to run docker and train a small data set, there should be no error, and it should use GPU instead of CPU.

So, my question now becomes: is there a way to assume the necessary memory to train and track data set?

**Comment by willgraf** [comment]
Unfortunately, the method in `deepcell` version 0.9.0 does not scale well with the number of objects to track. We are currently working on a new cell tracking method which should make it into the next release (0.10.0).

However, I don't think it should cause any OOM resource issues. To reduce the memory footprint I might try 1) reducing the batch size, or 2) resizing the input images.

**Comment by jizhouh** [comment]
After playing with the tracker for several days, I figure out all the problems on running it. Thanks a lot.
