### ISSUE TITLE
Recommended patch/tile size for pretrained networks

### ISSUE THREAD

**Issue by lstrgar** [vanvalenlab/deepcell-tf#552]
Hi. Is there a recommended input size (HxW)? Specifically mesmer segmentation. Thanks in advance.

**Comment by ngreenwald** [comment]
Hey Luke, 
For the deepcell.org website we have a cap of 2048x2048 for bandwidth purposes. If you're running locally, image size is limited by GPU memory. There won't be any significant accuracy differences for larger or smaller images. Anything above 256x256 is automatically tiled and smoothed to make predictions.

**Comment by lstrgar** [comment]
Thanks for the information.
