### ISSUE TITLE
TNBC_DNA.tiff and TNBC_Membrane.tiff

### ISSUE THREAD

**Issue by igordot** [vanvalenlab/deepcell-tf#557]
The [deepcell.applications](https://deepcell.readthedocs.io/en/master/API/deepcell.applications.html) docs contains the following example:

```
# Load the images
im1 = imread('TNBC_DNA.tiff')
im2 = imread('TNBC_Membrane.tiff')
```

Are those images available somewhere?

**Comment by igordot** [comment]
No problem.

As you mentioned, `intro-to-deepcell/pretrained_models/resources` has some images. It looks like `example_input_*.tif` ones might be slightly cut off. I see a small band on the bottom. Is that expected?

**Comment by willgraf** [comment]
I'll let @ngreenwald chime in to, but I believe it is expected.
