### ISSUE TITLE
Error building docker container with newest version

### ISSUE THREAD

**Issue by vanvalen** [vanvalenlab/deepcell-tf#568]
**Describe the bug**
This error arises when building with docker:

manifest for tensorflow/tensorflow:2.5.2-gpu not found: manifest unknown: manifest unknown 

**To Reproduce**
1. Run  'sudo docker build -t $USER/deepcell-tf:latest .'

**Expected behavior**
I expected the docker container to build.

**Screenshots**
"Sending build context to Docker daemon  137.8MB
Step 1/10 : ARG TF_VERSION=2.5.2-gpu
Step 2/10 : FROM tensorflow/tensorflow:${TF_VERSION}
manifest for tensorflow/tensorflow:2.5.2-gpu not found: manifest unknown: manifest unknown"

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04

**Additional context**
I don't think the tensorflow:2.5.2-gpu tag exists on docker hub

**Comment by willgraf** [comment]
Yep, TensorFlow released the latest version for pip but the docker image is not yet built. Our CI/CD doesn't test for Docker so I did not notice this.

I assume that 2.5.2-gpu will be available within the next couple of days.

When 2.5.2-gpu tag is available, there will be new patch releases for 0.10.x and 0.11.x.
