### ISSUE TITLE
Warning when loading Mesmer model with tensorflow 2.5

### ISSUE THREAD

**Issue by jacobrosenthaldfci** [vanvalenlab/deepcell-tf#569]
When loading the pretrained Mesmer model with tensorflow 2.5, we get a warning indicating that the model was saved with a previous version of tensorflow. Code to reproduce:

````python
from deepcell.applications import Mesmer
app = Mesmer()
````
> ````WARNING:tensorflow:SavedModel saved prior to TF 2.5 detected when loading Keras model. Please ensure that you are saving the model with model.save() or tf.keras.models.save_model(), *NOT* tf.saved_model.save(). To confirm, there should be a file named "keras_metadata.pb" in the SavedModel directory.````

This is with deepcell v0.11.0 and tensorflow v2.5.2

Just wanted to confirm that it's ok to ignore this warning when using the model for inference?

Thanks so much!

**Comment by willgraf** [comment]
Yep, the warning is harmless and can be safely ignored.

The `TF_CPP_MIN_LOG_LEVEL` variable can be tweaked to prevent these from getting logged.

**Comment by willgraf** [comment]
If you encounter any issues while using `Mesmer`, please don't hesitate to open a new issue.
