### ISSUE TITLE
multipage tiff with different resolution between Z and XY

### ISSUE THREAD

**Issue by acycliq** [vanvalenlab/deepcell-tf#573]
Hi

Sorry if this is not the best place to post this. Let's say we have a multipage 3D tiff and the resolution in both X and Y dimensions is 0.165 pixels per micron. Let's also assume that the z-stack spacing between any two consecutive frames is 1 micron, hence resolution on Z will be 1 micron per pixel.
When it comes to segmenting this 3D image, this difference in the resolution, is this something I should worry about or it is handled somehow on deepcell's side?

Thanks

**Comment by ngreenwald** [comment]
Which model are you hoping to use to analyze this data? Mesmer, the nuclear tracking model, the time series model?

**Comment by acycliq** [comment]
The `nuclear `  I would say. This is how I am doing it: (assuming that  `my_mpp`  below is some float value). Also, in case that matter, time lapses are not relevant to my data. It is just a 3d dapi segmentation I am after; I do not have any cell lineages to build.
```
 app = NuclearSegmentation()
 print('Training Resolution:', app.model_mpp, 'microns per pixel')
 y_pred = app.predict(img, image_mpp=my_mpp, batch_size=2)
```

**Comment by willgraf** [comment]
The `NuclearSegmentation` application is for 2D data. If you pass in a zstack of N frames (of the shape `(N, X, Y, 1)`), then the application assumes that each of the `N` frames is an independent batch.

**Comment by acycliq** [comment]
What is the correct way to segment a 3D image (a stack of N frames) then? Is it `Mesmer `maybe, and how the difference in the resolution between Z and XY should be handled?

**Comment by ngreenwald** [comment]
Right now none of the available pretrained models explicitly perform 3D segmentation; instead, each frame is segmented separately and then stitched together after the fact with post-processing.

**Comment by acycliq** [comment]
Ok, thanks for clarifying this.

**Comment by willgraf** [comment]
All the pre- and post-processing are handed by the [`Mesmer` application](https://github.com/vanvalenlab/deepcell-tf/blob/master/deepcell/applications/mesmer.py), which processes single frames at a time.

**Comment by willgraf** [comment]
I'm going to close this issue as I believe the question is answered, but please follow up if there is more we can help with.
