### ISSUE TITLE
Problems with GPU library

### ISSUE THREAD

**Issue by Shigeaki-Kanatani** [vanvalenlab/deepcell-tf#574]
Describe the bug
We are running nuclei segmentation application, one warning raised when we load the segmentation app as you can see:

W: tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcusolver.so.11'; dlerror: libcusolver.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/shigeaki/anaconda3/envs/deepcell/lib/python3.9/site-packages/cv2/../../lib64:

It recognized our GPU, but the library was missing therefore our GPU registration was skipped.

Expected behavior
I would like my GPU to be properly registered

Screenshots

https://user-images.githubusercontent.com/55106354/148772250-f9c38509-ed55-43d7-87a0-e82f2bfc3d61.png

Desktop (please complete the following information):

    OS: Ubuntu 20.04.3 LTS
    Python3.9.7
    tensorflow2.5.1

**Comment by willgraf** [comment]
Is this a problem with a vanilla `tensorflow/tensorflow:2.5.1-gpu` image?

Can you please update the issue with your CUDA/NVIDIA driver versions and GPU?

**Comment by Shigeaki-Kanatani** [comment]
Hello, 

my CUDA is 11.5. NVIDIA driver is 495.29.05. 
GPU is RTX A5000 
We are running locally in Jupyter notebook

**Comment by willgraf** [comment]
Can you please confirm if you are having this issue with the base tensorflow image,  `tensorflow/tensorflow:2.5.1-gpu`?

**Comment by Shigeaki-Kanatani** [comment]
Hello, thank you for your quick response.

I just installed tensorflow using following command. Is this the base tensorflow image or not?

conda install tensorflow==2.5.1

**Comment by willgraf** [comment]
Ah excuse me, I thought you were using Docker.

Yes, that is the correct version of tensorflow. Can you confirm if tensorflow can see your GPU?

```
import tensorflow as tf
tf.test.gpu_device_name()
```

**Comment by Shigeaki-Kanatani** [comment]
Hello, 

This is my result. It found my GPU but failed to register it.

https://user-images.githubusercontent.com/55106354/148817331-e0676cf1-58ba-450f-8f7c-aa282539fccc.png

**Comment by willgraf** [comment]
TensorFlow cannot see your GPU. I bet that this is a problem related to either:
- tensorflow itself not being installed properly (maybe because of conda?)
- your GPU drivers not being set up properly / being incompatible with tensorflow.

To test the latter, you could see if the tensorflow Docker image mentioned above can read the device. If the Docker container can read the GPU, but your locally installed version cannot, then I'm confident it is a library installation issue.

**Comment by Shigeaki-Kanatani** [comment]
Hi,

Thank you for your good suggestions. Unfortunately, we are not familiar with Docker, so it may take time for us to test what you suggested. Do you know other ways to check TensorFlow installation?

**Comment by willgraf** [comment]
I would start with the [TensorFlow GPU docs](https://www.tensorflow.org/install/gpu).

**Comment by willgraf** [comment]
I'm going to close this issue as it seems to be an issue with either tensorflow installation or with GPU drivers, and NOT with the deepcell codebase.

But please follow up if/when you resolve the issue!
