### ISSUE TITLE
Soften NumPy requirements

### ISSUE THREAD

**Issue by FiReTiTi** [vanvalenlab/deepcell-tf#579]
**Is your feature request related to a problem? Please describe.**
Yes.
The current deepcell version requests _numpy<1.20_, which is a big constraint when NumPy current version is 1.22.2, and many libraries have started to impose _numpy>=1.20_

**Describe the solution you'd like**

If possible/compatible

    numpy>=1.16.6,<1.22

instead of

    numpy>=1.16.6,<1.20

**Describe alternatives you've considered**
In order to fix this constraint that creates an incompatibility with other libraries I do need, I have to first install deepcell, force and upgrade of numpy, then install all the others libraries.

**Comment by msschwartz21** [comment]
Unfortunately we currently have other libraries in the DeepCell ecosystem that are pinned to lower versions of numpy. Thank you for making us aware of the limitation. I'll leave this issue open so that it can go on our to do list for future releases of the library.

**Comment by FiReTiTi** [comment]
Ok, thank you for your answer.
It's unfortunate.
I'll keep a look for new releases with soften dependencies requirements as this creates big problems with more recent libraries  I have to use.

**Comment by willgraf** [comment]
I think that the numpy strictness is due to a bad release of numpy 1.20, which should be resolved in 1.20.3+.

I think `setup.py` could be updated to disallow the earlier releases of 1.20.x and the issue should be resolved in future versions.

**Comment by msschwartz21** [comment]
This issue should be resolved by the 0.12.0 release.

**Comment by FiReTiTi** [comment]
Thank you, I'll test it.

**Comment by FiReTiTi** [comment]
Thank you, it fixed all the my issues.

**Comment by FiReTiTi** [comment]
@msschwartz21 I talked to quickly.
It fixed the issues to install Mesmer along with other packages, but now there is a bug when running:

    ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

Here is the complete trace:

    Traceback (most recent call last):
      File "/home/groups/graylab_share/data/thibaulg/Marilyne/./Dataset01 - Segmentation/tmp/Script.py", line 5, in <module>
        from deepcell.applications import Mesmer
      File "/home/groups/graylab_share/OMERO.rdsStore/thibaulg/Python/Python39_cycIFAAP/lib/python3.9/site-packages/deepcell/__init__.py", line 34, in <module>
        from deepcell import applications
      File "/home/groups/graylab_share/OMERO.rdsStore/thibaulg/Python/Python39_cycIFAAP/lib/python3.9/site-packages/deepcell/applications/__init__.py", line 32, in <module>
        from deepcell.applications.application import Application
      File "/home/groups/graylab_share/OMERO.rdsStore/thibaulg/Python/Python39_cycIFAAP/lib/python3.9/site-packages/deepcell/applications/application.py", line 37, in <module>
        from deepcell_toolbox.utils import resize, tile_image, untile_image
      File "/home/groups/graylab_share/OMERO.rdsStore/thibaulg/Python/Python39_cycIFAAP/lib/python3.9/site-packages/deepcell_toolbox/__init__.py", line 41, in <module>
        from deepcell_toolbox.compute_overlap import compute_overlap
      File "deepcell_toolbox/compute_overlap.pyx", line 1, in init deepcell_toolbox.compute_overlap
    ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

It seems to be happening with Numpy 1.21.6

Do you want me to open a new ticket/issue?

**Comment by msschwartz21** [comment]
Can you try creating a fresh environment to install deepcell in? I saw this issue earlier today when I accidentally installed deepcell 0.11.2 in a docker container based on deepcell 0.12.0.

**Comment by FiReTiTi** [comment]
It's a fresh Conda environment dedicated to only my pipeline which can use Mesmer for nuclei segmentation.

**Comment by msschwartz21** [comment]
Can you send me your requirements for the install of all deepcell related packages?

**Comment by FiReTiTi** [comment]
I installed it in my cycIFAAP pipeline, so "pip install cycIFAAP" if you want to test.
Else, cycIFAAP requirements are:
`FiReTiTiPyLib>=1.4.2`
`numpy>=1.21.5`
`cellpose<2.0,>=1.0.2`
`DeepCell>=0.12.0`
And FiReTiTIPyLiB requires:
glob2>=0.7
graphviz>=0.8
horology>=1.1.0
imagecodecs>=2021.5.20
imageio>=2.9.0
matplotlib>=3.4.2
natsort>=7.1.0
numpy>=1.21.5
opencv-contrib-python-headless>=4.5.5
opencv-python-headless>=4.5.5
pandas>=1.2.4
Pillow>=8.2.0
psutil>=5.8.0
qtconsole>=5.1.0
QtPy>=1.9.0
scikit-image<0.19,>=0.18.3
scikit-learn>=0.24.2
scipy>=1.6.3
seaborn>=0.11.1
sklearn>=0.0
spams>=2.6.2.5
tifffile>=2021.4.8
torch<1.8,>=1.7.1
torchvision<0.9,>=0.8.2
tornado>=6.1
wheel>=0.37.0

I'll try to install an older numpy version and see how it goes.

**Comment by FiReTiTi** [comment]
Update for various numpy versions:
 - 1.21.1 fails
 - 1.21.6 fails
 - 1.22.4 success (no error).

**Comment by msschwartz21** [comment]
What version of python are you working on? I checked our tests and we install numpy 1.21.6 in our python 3.7 environment and everything works.

**Comment by FiReTiTi** [comment]
Python 3.9.12
