### ISSUE TITLE
Import error from cv2 and numpy

### ISSUE THREAD

**Issue by juliannaharwood** [vanvalenlab/deepcell-tf#588]
Hello, I am new to deepcell and attempting to use it in a Colab notebook. I encounter the following error on import just after installing via pip: 

`ImportError: cannot import name '_registerMatType' from 'cv2.cv2' (/usr/local/lib/python3.7/dist-packages/cv2/cv2.cpython-37m-x86_64-linux-gnu.so)` 

which I can remediate by reverting to an earlier version of opencv-python-headless: 

`pip install opencv-python-headless=='4.1.2.30'`

However, then I encounter this error on import:

`ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject` 

which seems to be associated with the `numpy<1.20.0,>=1.16.6` requirement, because if I upgrade numpy then I am able to import successfully, but then cannot use the PanopticNet, as the following code results in an error:

```
from deepcell.model_zoo.panopticnet import PanopticNet

classes = {
    'inner_distance': 1,  # inner distance
    'outer_distance': 1,  # outer distance
    'fgbg': 2,  # foreground/background separation
}

model = PanopticNet(
    backbone='resnet50',
    input_shape=(128, 128, 1),
    norm_method='std',
    num_semantic_classes=classes)
```

`NotImplementedError: Cannot convert a symbolic Tensor (location/meshgrid/Size:0) to a numpy array. This error may indicate that you're trying to pass a Tensor to a NumPy call, which is not supported`

The full Colab notebook is attached as a PDF so you can see the full error messages and Traceback. 

Thank you in advance for the help!
[deepcell_test.pdf](https://github.com/vanvalenlab/deepcell-tf/files/8466188/deepcell_test.pdf)

**Comment by msschwartz21** [comment]
Hi Julianna! I was able to reproduce the error you described in Google Colab and I am looking into some possible ways to fix it. In the meantime, if you have access to local or cloud computing resources, we recommend using Docker containers to run deepcell (https://deepcell.readthedocs.io/en/master/#install-with-docker).

**Comment by juliannaharwood** [comment]
Hi Morgan, thanks for getting back to me. I'll ultimately be running the models in AWS, so will look into using Docker to run it.

**Comment by JoeBlackSci** [comment]
Hello, 
I'm having a similar problem to Julianna in that I have to work around the same import issues that have been described. 
Once this is done, I am unable to run `app.predict()` and am met with the following error:  

```
UnknownError:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node panopticnet/conv_channels/Conv2D (defined at /usr/local/lib/python3.7/dist-packages/deepcell/applications/application.py:338) ]] [Op:__inference_predict_function_71359]
```

The colab notebook used to work fine previously, perhaps there has been some issue with the dependencies and google colab upgrading from python3.6 to 3.7.

**Comment by JoeBlackSci** [comment]
I'd like to say that with the current release of deepcell and the example notebooks. This is issue no longer presents. The notebooks now work perfectly on google colab, python 3.7.

**Comment by msschwartz21** [comment]
Thank you for the update! I'll close this issue for now, but feel free to reopen if further issues emerge.
