### ISSUE TITLE
Using Deepcell to segment images

### ISSUE THREAD

**Issue by Ati-74** [vanvalenlab/deepcell-tf#608]
Hi.
I have a mono agarose dataset for E.coli.
I performed segmentation of the last time step of this dataset using the DeepCell server, but as you can see, the result is not good.
The Deppcell team has developed a pre-trained model of nuclear and/or whole-cell segmentation of cell culture with about 75,000 images, but I do not have a huge dataset (I have about 2000 images in my datasets), so would you think creating a segmentation model from my own data would be more effective?
What do you suggest I do if you think I should train a segmentation model? You train the segmentation model using Npz files instead of .tif files (my images are .tif)

**Comment by msschwartz21** [comment]
Hi Atiyah, you could train a model on your own dataset if you have ground truth annotations. However you might want to checkout the [DeLTA](https://gitlab.com/dunloplab/delta) package from the Dunlop Lab which was designed for bacterial segmentation.

**Comment by Ati-74** [comment]
So you would suggest DeLTA to segment and process my images?

**Comment by msschwartz21** [comment]
I would try DeLTA first before working on training your own model.
