### ISSUE TITLE
Pixel values of predictions output

### ISSUE THREAD

**Issue by jayluo2** [vanvalenlab/deepcell-tf#615]
Hello, 
I am using the Mesmer object with pretrained weights (“app”) for segmentation in Python code. While the predictions from app.predict() appear to have distinct pixel values for each cell, the image itself seems to be on a gradient from top to bottom (from lower to higher pixel values). Is this behavior expected? I ask because the colored cells in the example predictions output on this page (https://github.com/vanvalenlab/intro-to-deepcell/tree/master/pretrained_models) do not appear to be on any color/pixel value gradient.

**Comment by ngreenwald** [comment]
Yes, that is the expected behavior. We use that color format for visualization purposes, but the raw model outputs have sequentially named cells from top to bottom as a result of running `skimage.label`

**Comment by jayluo2** [comment]
Got it, thanks!
