### ISSUE TITLE
Questions about using RGB images to inference

### ISSUE THREAD

**Issue by gaojunbin** [vanvalenlab/deepcell-tf#626]
Hi,
Thanks for developing this useful tool! I’m eager to apply it in our research.
However, I found the input of your model is the original data read by microscope which contains 2 channels. And the max/mean of these data resemble so large (>>255). I have some image data (*.tif) which contains 3 channels (RGB).  I want to know are there any methods to use your pre-trained model to process these RGB data. I don't have any segmentation annotations so I can not retrain by myself. However, I want to use your model trained well to extract useful features/embedding for our research. Can you help me what should I do?

Meanwhile, the resolution of my data is around 10k * 10k, I may cut it to 512*512 as a patch and merge the result in the post processing. Is it feasible?

Here is an example of the data:
[www.junbin.xyz/reference/20220922.png](http://www.junbin.xyz/reference/20220922.png)

**Comment by ngreenwald** [comment]
The model expects two channels of image data, one for the nucleus and one for the membrane. If your RGB data has three colors, you can select only the relevant channels for processing. Alternatively, if you have multiple nuclear or membrane channels, you can merge them together and then run them through the model. 

The absolute values of the image intensity isn't important, it will automatically be rescaled by the model. The web-based version of Mesmer doesn't support large images, but you can run it locally on your GPU with very large images.
