### ISSUE TITLE
Potentially unused function `export_utils.export_model_to_tflite`

### ISSUE THREAD

**Issue by rossbar** [vanvalenlab/deepcell-tf#645]
This is another potential issue identified by the linter. If this function were ever called, it would raise an exception due to the fact that one of the variables is undefined:

https://github.com/vanvalenlab/deepcell-tf/blob/17b54eb26ebcf0e373b7e46b2ca353b5374da2f9/deepcell/utils/export_utils.py#L135

The `export_model_to_tflite` function isn't tested and doesn't appear to be called anywhere else internally.

The simple fix would be to rename the variable `tflite_quant_model` -> `tflite_model`, but the fact that this function doesn't appear to be used/tested (nor reported in the issue tracker) made me think that it might also be a candidate for deprecation.

**Comment by msschwartz21** [comment]
I support deprecating this function. I think we abandoned tflite a long time ago, but I think @vanvalen could confirm.

**Comment by vanvalen** [comment]
Yes abandon it.

Dave
