### ISSUE TITLE
Code for Nature paper model

### ISSUE THREAD

**Issue by Vadori** [vanvalenlab/deepcell-tf#654]
Hi, 
First of all, thanks for open-sourcing the code of deep cell. 
Then, I have been looking for the code to create the same model you described in the mesmer/deepcell Nature paper, where you write that you used two semantic heads to predict the inner distance (not the outer) and a pixel class (border/background/foreground). I was not able to find it within GitHub. Can you please help me with this? How should I set the parameters of the panoptic model to get the same semantic heads? And is it possible to process this type of output with the current version of the watershed post-processing? Or is the model in the paper outdated and we should consider the combination of inner and outer distance and only background/foreground classification?

Thank you!!

**Comment by ngreenwald** [comment]
Hi @Vadori, all of the code necessary to recreate the paper, including model training, can be found in this github repo: https://github.com/vanvalenlab/publication-figures/tree/master/2021-Greenwald_Miller_et_al-Mesmer. 

There is also a Mesmer notebook in the deepcell-tf repo which you can use to run (and postprocess) the mesmer output using the watershed function: https://github.com/vanvalenlab/deepcell-tf/blob/master/notebooks/applications/Mesmer-Application.ipynb

**Comment by Vadori** [comment]
Thanks, @ngreenwald!

**Comment by ngreenwald** [comment]
No problem
