### ISSUE TITLE
Question about training/retraining mesmer model

### ISSUE THREAD

**Issue by pr4deepr** [vanvalenlab/deepcell-tf#663]
Hi
  Thanks a lot for creating this useful resource. 
I haev a question about training or retraining a Panoptic net model? 

Currently, I am using the approach here: 
https://github.com/vanvalenlab/deepcell-tf/blob/master/notebooks/applications/Mesmer-Application.ipynb
to segment an image with nuclei and membrane channel. 

Is it possible to retrain this model on custom data? 

Looking at the training approach here: https://deepcell.readthedocs.io/en/master/notebooks/Training-Segmentation.html
it looks like its training from scratch? 

Also, can I combine my custom data with any of the datasources here for training?
 https://github.com/vanvalenlab/deepcell-tf/blob/96aa1f429381edc0db0e962984482c72c0cf2ac8/deepcell/datasets/__init__.py
 

Cheers
Pradeep

**Comment by rossbar** [comment]
Yes - it is indeed possible to train the model on different input data. I believe the Training-Segmentation notebook you've found is the best place to start.

Re: combining datasets - that is indeed also possible, but left to the user to implement!

**Comment by pr4deepr** [comment]
will reopen this if I have any questions
