### ISSUE TITLE
Tensorflow issue in Mesmer

### ISSUE THREAD

**Issue by ashishshel** [vanvalenlab/deepcell-tf#683]
**Describe the bug**
I am getting a Tensorflow UNKNOWN ERROR (34) when I try to run the Mesmer app from the python notebook.
I am running the notebook from a docker based installation on a linux spin up instance. This is a non-gpu installation. 
Please see attached screenshot.
**Desktop (please complete the following information):**
 - OS: Ubuntu Linux 
 - 20.04
 - Python Version : 3.10
<img width="1328" alt="Screenshot 2023-08-07 at 3 53 39 PM" src="https://github.com/vanvalenlab/deepcell-tf/assets/78761160/1234843e-753e-4482-ab04-bde7abf8c96c">

**Comment by rossbar** [comment]
This is expected - `tensorflow` is particularly verbose at import time. The rest of the example should run fine despite the warnings.

If that's not the case, then you should double-check that you are using the correct image - i.e. `:latest` vs. `:latest-gpu`. I'd actually expect both to work, though you may get strange behavior/more warnings if you're using the `:latest-gpu` container on a system without gpu support.

**Comment by AnuragNagare** [comment]
Check TensorFlow Version Compatibility:
Ensure that the version of TensorFlow you're using is compatible with the version of Mesmer and other dependencies you have. TensorFlow might not work well with the latest version of Python 3.10, so consider using a stable version like TensorFlow 2.7.

Check Dependency Versions:
Verify that all the dependencies, including Mesmer and any other libraries you're using, are compatible with each other. Mismatched dependencies can lead to unexpected errors.

Update or Reinstall Libraries:
Update all your libraries to their latest compatible versions. You might also consider uninstalling and reinstalling TensorFlow and other relevant packages to ensure a clean setup.

Check Docker Configuration:
If you're using Docker, ensure that your Docker image is set up correctly. The image should include the required libraries and dependencies. Sometimes, running in a Docker container might require specific configurations.

**Comment by rossbar** [comment]
I will close this as I don't think there is anything actionable here. If the problem persists, feel free to reopen with a minimal reproducing example.
