### ISSUE TITLE
Incompatible shape of testing dataset in Nuclear Segmentation notebook

### ISSUE THREAD

**Issue by bnovotny** [vanvalenlab/deepcell-tf#686]
**Describe the bug**
When running the "Nuclear Segmentation - DeepWatershed.ipynb" notebook on the DynamicNuclearNet Segmentation dataset, I am experiencing an error where the input shape of the model does not match the shape of the training data.

**To Reproduce**
1. Run the Nuclear Segmentation - DeepWatershed.ipynb on the DynamicNuclearNet Segmentation dataset up to "Predict on Test Data".
2. Run the line `test_images = prediction_model.predict(X_test)`
3. See error

**Expected behavior**
Test should complete without errors.

**Screenshots**
Here is the full text of the error: 
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/tmp/ipykernel_1/2407456956.py in <module>
      1 X_test = histogram_normalization(X_test)
      2 
----> 3 test_images = prediction_model.predict(X_test)

~/.local/lib/python3.7/site-packages/keras/utils/traceback_utils.py in error_handler(*args, **kwargs)
     65     except Exception as e:  # pylint: disable=broad-except
     66       filtered_tb = _process_traceback_frames(e.__traceback__)
---> 67       raise e.with_traceback(filtered_tb) from None
     68     finally:
     69       del filtered_tb

~/.local/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py in autograph_handler(*args, **kwargs)
   1145           except Exception as e:  # pylint:disable=broad-except
   1146             if hasattr(e, "ag_error_metadata"):
-> 1147               raise e.ag_error_metadata.to_exception(e)
   1148             else:
   1149               raise

ValueError: in user code:

    File "/home/jupyter/.local/lib/python3.7/site-packages/keras/engine/training.py", line 1801, in predict_function  *
        return step_function(self, iterator)
    File "/home/jupyter/.local/lib/python3.7/site-packages/keras/engine/training.py", line 1790, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/home/jupyter/.local/lib/python3.7/site-packages/keras/engine/training.py", line 1783, in run_step  **
        outputs = model.predict_step(data)
    File "/home/jupyter/.local/lib/python3.7/site-packages/keras/engine/training.py", line 1751, in predict_step
        return self(x, training=False)
    File "/home/jupyter/.local/lib/python3.7/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "/home/jupyter/.local/lib/python3.7/site-packages/keras/engine/input_spec.py", line 264, in assert_input_compatibility
        raise ValueError(f'Input {input_index} of layer "{layer_name}" is '

    ValueError: Input 0 of layer "panopticnet" is incompatible with the layer: expected shape=(None, 256, 256, 1), found shape=(None, 512, 512, 1)
```

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: 20.04.6
 - Python Version: 3.7.12
 - DeepCell Version: 0.12.5

**Additional context**
It seems that the testing data is 512x512, while the model is expecting 256x256. Is there a step where I should be cropping the testing data? If I change the input shape of the model, I get "out of memory" errors.

**Comment by rossbar** [comment]
This was likely fixed in either #671 or #673 - the easiest thing to do would be to try with deepcell version 0.12.6 or greater.

**Comment by bnovotny** [comment]
Thank you for your response! I upgraded to deepcell version 0.12.7, but I am experiencing the same error. Is there anything else I can try?

**Comment by rossbar** [comment]
Hmm I suspect this is a data versioning problem then. Where/how did you get the data stored in `notebooks/data`? Does that data have a version/hash associated with it?

**Comment by bnovotny** [comment]
I downloaded the DynamicNuclearNet Segmentation dataset Version 1.0 from https://datasets.deepcell.org/data.

The notebook actually suggests downloading the tracking dataset, but I noticed that those files are .trks rather than the .npz files called for in the code.

**Comment by rossbar** [comment]
I took a look at this last night and I think that the notebook is a bit out-of-date. Even without the shape issue, there are missing imports & undefined variables that will prevent it from running.

All that's to say this will likely require a bit more elbow grease to get working :). Fortunately however, since the images are square and the expected shape is a factor of two less, you might be able to get away with a simple reshape (untested); e.g.

```python
>>> X_test.shape  # original shape
(717, 512, 512, 1)
>>> X_test = X_test.reshape(
...     (X_test.shape[0] * 4, X_test.shape[1] // 2, X_test.shape[2] // 2, 1)
... )
>>> X_test.shape
(2868, 256, 256, 1)
```

**Comment by bnovotny** [comment]
Reshaping X_test and y_test worked, thanks so much for looking into this! For reference I also had to remove this line for the dimensions to match up in the "Evaluate Results" block: `y_pred = np.expand_dims(y_pred, axis=-1)` . Really appreciate your time, thanks for the great package :)
