### ISSUE TITLE
Access token needed

### ISSUE THREAD

**Issue by liuyangzzu** [vanvalenlab/deepcell-tf#702]
Dear author,

I have applied the token for my account: yang.liu@jax.org one week before. But I haven't got your reply. Would you please help me to get my token? Thank you!

Best regards,

Yang

**Comment by rossbar** [comment]
Hi @liuyangzzu , the jax.org domain has been added to the allowlist so all requests originating from that domain should automatically be approved. Thanks for raising this and please feel free to reopen if you have further issues.
