### ISSUE TITLE
Segmentation Mask Output

### ISSUE THREAD

**Issue by tbudiman7** [vanvalenlab/deepcell-tf#703]
Hi VanValen Lab, 

We have successfully generated segmentation masks using Mesmer and when we opened them on Fiji, the masks look like cell outlines. However, this is causing problems in our downstream analysis which were never a problem when we used segmentation masks generated by Ilastik and CellProfiler. I have attached images of both segmentation masks below, the one generated by Ilastik is filed in whereas the one on Mesmer is not. Is there a way to generate masks with filed holes? 

Thank you. 

![Mesmer seg mask](https://github.com/vanvalenlab/deepcell-tf/assets/151666851/e992bf50-77b0-48da-b075-87a8870bf9bc)
![Ilastik seg mask](https://github.com/vanvalenlab/deepcell-tf/assets/151666851/00907523-edf0-4b0b-8be2-e92bc16b814f)

**Comment by rossbar** [comment]
The masks produced by mesmer is a label image, i.e. where each pixel that corresponds to an instance of an individual cell is assigned a value corresponding to the index of the cell. In other words, the masks from mesmer are "filled in" - the fact that you're only seeing mask outlines likely has something to do with how Fiji is configured to load data.

**Comment by tbudiman7** [comment]
Thank you for clarifying, that is really helpful. This was what we suspected as well but when we use the mask for analysis using the imcRtools pipeline to map marker expression back onto the mask image it does not seem to work when it did with the Ilastik segmentation mask. Using the mesmer generated mask resulted in an figure with just the segmentation mask outline instead of a "filed in" mask that shows marker expression levels. Do you know what could have resulted in this problem?
