### ISSUE TITLE
Segmentation Mask FIle Issues

### ISSUE THREAD

**Issue by tbudiman7** [vanvalenlab/deepcell-tf#704]
Hi VanValen Lab,

We are using a Mesmer standalone program to generate segmentation masks and then inputting it to steinbock. We are running into an issue where when steinbock generates object intensities for each sample, the resulting csv files will show that only 255 cells are present in each sample. We know this is not correct and seems to be an issue with our Mesmer generated segmentation masks because when we retried steinbock with masks generated by Ilastik/CellProfiler steinbock will list out a number of cells in the correct range. 

I have attached an image of the code we use to export our segmentation mask. 
<img width="983" alt="Screenshot 2023-12-19 at 3 53 10 PM" src="https://github.com/vanvalenlab/deepcell-tf/assets/151666851/1f7c5175-108e-4df3-8c14-7a049081404a">

**Comment by rossbar** [comment]
Again, this is an issue with the remainder of the pipeline not with mesmer itself. When using default parameters, the `Mesmer.predict` method will return masks with dtype int32, which are capable of representing segmentation masks with over 2 billion cells.

Changing the dtype of the mask can cause overflows if you use dtypes that are not capable of representing the number of cells in the image; however, this is part of your pipeline and not Mesmer itself.
