### ISSUE TITLE
MacBook M3 support, DeepCell cannot be installed due to tensorflow version

### ISSUE THREAD

**Issue by adrianomartinelli** [vanvalenlab/deepcell-tf#705]
**Describe the bug**
Not possible to install DeepCell on MacBook M3

**To Reproduce**
```
pip install DeepCell
```

This errors with 

```
The conflict is caused by:
    deepcell 0.12.9 depends on tensorflow~=2.8.0
    deepcell 0.12.8 depends on tensorflow~=2.8.0
    deepcell 0.12.7 depends on tensorflow~=2.8.0
    deepcell 0.12.6 depends on tensorflow~=2.8.0
    deepcell 0.12.5 depends on tensorflow~=2.8.0
```

However, the older version available is 2.13
```
pip index versions tensorflow  # Available versions: 2.15.0, 2.14.1, 2.14.0, 2.13.1, 2.13.0
```

**Expected behavior**
install DeepCell

**Desktop (please complete the following information):**
- Apple M3 Pro
 - OS: macOS Sonoma
 - Version 14.1
 - Python Version 3.8, 3.9, 3.10

**Additional context**
I also tried to create a Docker image from python:3.8-slim and install DeepCell in there but this fails as well.
With that approach only tensorflow 2.10 is available but not ~=2.8.0

**Comment by rossbar** [comment]
This is expected - `deepcell-tf` currently depends on tensorflow 2.8, so the system you'd like to install on must support this. I'm not sure what the status is with arm wheels for older versions of tensorflow, so you may need to build tensorflow from source.

**Comment by yubin-ai** [comment]
I can confirm that this issue is on another M chip apple device as well.
