### ISSUE TITLE
Align for multi fov result combined 

### ISSUE THREAD

**Issue by ustc-fmh** [vanvalenlab/deepcell-tf#710]
Hi, Due to the large memory consumption of the experimental data, I am currently using manual segmentation into n small fov for deepcell cell segmentation, but there are obvious mis-segmentation at the edge of each small fov, I would like to know how to solve the problem of merging cell segmentation results at the edge area to reach align to generate the final cell segmentation result?

**Comment by rossbar** [comment]
This is a generic operation that is outside the scope of the segmentation model itself - the specific pre/post-processing of segmentations is left up to the user. When it comes to re-tiling segmentations from manually-tiled data, there are several things you could try including overlapping tiles.

I'm going to close this as there's nothing specifically actionable on the `deepcell-tf` side; if you come up with a solution that works for your usecase don't hesitate to share back so others with a similar problem can benefit!
