### ISSUE TITLE
DeepCell API Key SignUp page responds with a Server Error

### ISSUE THREAD

**Issue by adrianomartinelli** [vanvalenlab/deepcell-tf#712]
**Describe the bug**
I try to login with my credentials at https://users.deepcell.org/ which does not work.
Password reset  also does not work. 
If I want to sign-up, the server responds with an error upon form submission

**Comment by rossbar** [comment]
Did you register with an email address? If so, try dropping the `@whatever.whatever` part.

**Comment by adrianomartinelli** [comment]
Yes I registered with an email address structured like a***+***@***.com a while ago.
I tried to login with 

- a***+***@***.com
- a***+***
- a***

as username but neither works and through the password reset I do not receive as linke to reset the password.

**Comment by rossbar** [comment]
> Yes I registered with an email address structured like a***+***@***.com a while ago.

`.com` domains are automatically block-listed per the terms of the [deepcell-tf license](https://github.com/vanvalenlab/deepcell-tf/blob/master/LICENSE). The project is freely available for non-commercial use.

**Comment by adrianomartinelli** [comment]
okey that resolved the issue, I was able to sign up with my student account. Thanks!
