### ISSUE TITLE
API Token

### ISSUE THREAD

**Issue by sittnerr** [vanvalenlab/deepcell-tf#720]
Hi there,

I'm a new user for Deepcell and tried creating an account but can't login or receive an email when clicking on "forgot password". On the other hand, creating a new account using my email address doesn't work so I should pop up somewhere in the system. Is there a delay until I get access?
Thank you for your help!
Best regards,
Richard

**Comment by 925209391** [comment]
Mesmer Ethiopia

**Comment by rossbar** [comment]
>  Is there a delay until I get access?

Yes, unfortunately for non `.edu` domains there is no reliable way to generically probe whether a request originates from an academic institution thus these requests require manual review.
