### ISSUE TITLE
How to combine multiple membrane/cytoplasm channels?

### ISSUE THREAD

**Issue by bswhite** [vanvalenlab/deepcell-tf#723]
Hello,

The Mesmer manuscript says that multiple channels can be combined by adding their scaled values:
"For multiplexed datasets containing more than one high-quality nuclear or membrane marker, these channels were added together (after rescaling) ..."

What scaling do you recommend? Or, more relevant I suppose, what scaling did you use for training? min-max? z-scoring? 

Thank you,
Brian

**Comment by ngreenwald** [comment]
Hey @bswhite, 
Rescaling before summation is only needed if the channels have very different dynamic ranges. If they have similar intensities, then you can just add them together. 

We used CLAHE for rescaling, but I imagine many typical rescaling methods would work quite well, including z-score, 99th percentile, etc.

**Comment by rossbar** [comment]
I'll go ahead and close this as resolved, thanks @ngreenwald !
