### ISSUE TITLE
API token

### ISSUE THREAD

**Issue by mezwick** [vanvalenlab/deepcell-tf#724]
Morning,

Enthusiastic user of mesmer here :).

I requested an API token to use the latest Deepcell versions a while back, but have yet to receive one.

I guess the request was either missed, or not permitted as I work in industry? Though i'm pretty sure the licence terms don't prohibit industry users of the deepcell package?

Anywho. Useful to hear if that is the case! But if not, please could i get sent through the token. 

Thanks,
Merrick

**Comment by rossbar** [comment]
> I guess the request was either missed, or not permitted as I work in industry? Though i'm pretty sure the licence terms don't prohibit industry users of the deepcell package?

Indeed this is the reason. The license provides for attribution-based usage *only* for non-commercial use. See [the second bullet in the LICENSE](https://github.com/vanvalenlab/deepcell-tf/blob/master/LICENSE) for details.

**Comment by mezwick** [comment]
Thanks for the clarification. 

Will steer clear of using the Deepcell package for now to avoid any licensing issues, or reach out to vanvalenlab@gmail.com as per the license in case we decide to pursue use of Deepcell.
