### ISSUE TITLE
Unable to access nuclear segmentation and cell tracking models in Caliban-Application notebook tutorial

### ISSUE THREAD

**Issue by cdsyou** [vanvalenlab/deepcell-tf#728]
**Describe the bug**
Hi, I cannot seem to access the nuclear segmentation and cell tracking models following the Caliban-Application notebook tutorial

**To Reproduce**
Run 1:
from deepcell.applications import NuclearSegmentation
app = NuclearSegmentation()

Run 2:
from deepcell.applications import CellTracking
tracker = CellTracking()

Error:
Error 1:
TypeError: NuclearSegmentation.__init__() missing 1 required positional argument: 'model'

Error 2:
TypeError: CellTracking.__init__() missing 2 required positional arguments: 'model' and 'neighborhood_encoder'

**Expected behavior**
Instantiate nuclear segmentation application by  downloading latest model with pre-trained weights. Should also behave similarly for cell tracking class instantiation

**Screenshots**
![image](https://github.com/user-attachments/assets/89d902d6-df94-471f-89f9-40885fa96c0c)

**Desktop (please complete the following information):**
 - OS: Windows Version 10.0.22631 Build 22631
 - Python Version 3.10.14
 - Deepcell Version: 0.12.10

**Comment by rossbar** [comment]
Thanks for reporting @cdsyou , this was indeed changed recently in #721 and something I missed in review.

AFAICT there are two options:
 1. We keep the current behavior and require users to specify a `model` as input to the application and update the docs accordingly with an example model, or
 2. We revert back to making `model` an optional kwarg and add-back the logic to automatically choose a model for users.

@msschwartz21 WDYT, any preferences (or other ideas)?

**Comment by rossbar** [comment]
Upon closer inspection it looks like the updated model loading API is to use the `Application.from_version` class method, so it looks to me like this just needs a doc update!

**Comment by cdsyou** [comment]
Thank you for your reply @rossbar. Sorry, I am not sure if I am following - how should I instantiate the applications for segmentation and tracking?

**Comment by rossbar** [comment]
> Sorry, I am not sure if I am following - how should I instantiate the applications for segmentation and tracking?

With the latest version of deepcell-tf (v0.12.10), you have to specify what specific version of the model you want, so where before you would do:

```python
>>> app = NuclearSegmentation()
```

now, you would do:

```python
>>> app = NuclearSegmentation.from_version("1.1")
```

We'll be sure to get the docs updated to reflect the change.

**Comment by cdsyou** [comment]
That works! Thank you!
For cell tracking, however, 

tracker = CellTracking().from_version(version='1.1')

Still does not work- it gives the error output of:
TypeError: CellTracking.__init__() missing 2 required positional arguments: 'model' and 'neighborhood_encoder'

**Comment by rossbar** [comment]
Get rid of the parentheses - `from_version` is an alternative to
`__init__`, the default constructor.

**Comment by cdsyou** [comment]
Ah of course. Thank you that works! 

Just for the record I will leave the solution below:

tracker = CellTracking.from_version(version='1.1')

**Comment by Soroush-aali-bagi** [comment]
I get the following error and the users.deepcell.org does not allow me to register.
Please help me with this.

ValueError: 
DEEPCELL_ACCESS_TOKEN not found.
Please set your access token to the DEEPCELL_ACCESS_TOKEN
environment variable.
For example:

	export DEEPCELL_ACCESS_TOKEN=<your-token>.

If you don't yet have a token, you can create one at
https://users.deepcell.org
