### ISSUE TITLE
Magnification in TissueNet Dataset

### ISSUE THREAD

**Issue by lsnls** [vanvalenlab/deepcell-tf#732]
Hi, thank you for your outstanding work!

I readed your work titled `Whole-cell segmentation of tissue images with human-level performance using large-scale data annotation and deep learning`. Could you please let me know the magnification used in the TissueNet dataset? Is the magnification uniform throughout?

Thanks a lot! Looking forward to your reply!

**Comment by ngreenwald** [comment]
Almost all of the images are approximately 20x, with the exception of the IMC datasets, which are closer to 10x.

**Comment by lsnls** [comment]
Thanks a lot!
