### ISSUE TITLE
Request for Account Approval for DeepCell Token

### ISSUE THREAD

**Issue by ssaintsoon** [vanvalenlab/deepcell-tf#736]
Dear authors,

I recently attempted to create an account for obtaining a token
and noticed that non-edu account require manual review.

I have submitted two email addresses - ssaintsoon@gmail.com and J9049@snuh.org,
but I'm unsure if there are any issue with my domains due to license terms.

Could you kindly help me in obtaining an account for the DeepCell token?
I would greatly appreciate your help.

Best regards,

Kwon

**Comment by ssaintsoon** [comment]
I checked that my account is approved.
I'm deeply appreciated for your review! I will close this issue now.

Kwon

**Comment by ambeeblush** [comment]
Hi there!

I am also experiencing problems with my account, tried with two mail addresses (.it and .com), can I kindly ask you approximately how much time it takes to get the account approved and how the approval is notified? Thanks a lot!

**Comment by ssaintsoon** [comment]
Dear Ambra,

Sorry for super late response, as I miss the alarm.
I'm not sure the exact time but I've got approved within 5 days.
You may receive notifying e-mail for approval.

I hope you already got permission.
Sorry again for missing your ask.

Kwon
